In [ ]:
import torch, numpy as np
import torch.nn as nn
import torch.optim as optim
from NARNN import NARNN

criterion = nn.MSELoss()

print(type(criterion))
red_A1 = NARNN(input_dim=8, hidden_dim=0, output_dim=1, num_layers=0)

In [7]:
import torch
import torch.nn as nn

# Define una red de ejemplo
class MiRed(nn.Module):
    def __init__(self):
        super(MiRed, self).__init__()
        self.capa1 = nn.Linear(10, 5)
        self.capa2 = nn.Linear(5, 1)

mi_red = MiRed()

# Recorre las capas de la red para encontrar las capas de tipo nn.Linear
for nombre_capa, capa in mi_red.named_children():
    if isinstance(capa, nn.Linear):
        print(f"Nombre de la capa: {nombre_capa}")
        pesos = capa.weight
        sesgos = capa.bias
        print("Pesos:")
        print(pesos)
        print("Sesgos:")
        print(sesgos)


print(getattr(red_A1,"fc1").weight)

Nombre de la capa: capa1
Pesos:
Parameter containing:
tensor([[ 0.3144, -0.0202, -0.0108, -0.0429, -0.1464, -0.2823,  0.0104,  0.2925,
          0.2730,  0.2427],
        [ 0.1854,  0.3144,  0.0367, -0.2001, -0.0542, -0.1495,  0.0650, -0.0174,
          0.1961, -0.0806],
        [-0.0571, -0.1487, -0.1379,  0.1222,  0.0623, -0.1982,  0.3077, -0.1953,
          0.2836, -0.1059],
        [ 0.2721,  0.0785,  0.2622,  0.2319, -0.2343, -0.1718,  0.2329, -0.0472,
          0.0037, -0.1467],
        [ 0.1288,  0.2063, -0.2045, -0.1182, -0.1618,  0.0513,  0.1632, -0.0135,
         -0.2430, -0.2354]], requires_grad=True)
Sesgos:
Parameter containing:
tensor([ 0.1892, -0.0865, -0.0885,  0.0902, -0.0346], requires_grad=True)
Nombre de la capa: capa2
Pesos:
Parameter containing:
tensor([[ 0.3551,  0.2183, -0.4091, -0.0641, -0.0446]], requires_grad=True)
Sesgos:
Parameter containing:
tensor([0.0780], requires_grad=True)
Parameter containing:
tensor([[-0.0245, -0.3068,  0.2515,  0.3393, -0.3113,  0.

In [34]:
import torch
import torch.nn as nn
import torch.nn.functional as F
criterion = nn.MSELoss()

class NARNN(nn.Module):
    def __init__(self, parametros, input_dim, hidden_dim, output_dim, num_layers):
        super(NARNN, self).__init__()
        self.fc1 = nn.Linear(input_dim,10)
        self.fc2 = nn.Linear(10,10)
        self.fc3 = nn.Linear(10,output_dim)

    def forward(self, x):
        tan_sigmoid = lambda a : F.tanh(F.sigmoid(a))
        x = tan_sigmoid(self.fc1(x))
        x = F.logsigmoid(self.fc2(x))
        x = self.fc3(x)
        return x

red_A1 = NARNN([], input_dim=8, hidden_dim=0, output_dim=1, num_layers=0)
_input=torch.randn(8)

def func(*parametros):
    index = 0
    for capa, instancia in red_A1.named_children():
        # print(f"Nombre de la capa: {capa}")
        # print(f"Tamaño del peso de la capa: {getattr(red_A1,capa).weight.size()}")
        # print(f"Tamaño de la entrada: {parametros[index].size()}")

        # print(f"Tamaño del sesgo de la capa: {getattr(red_A1,capa).bias.size()}")
        # print(f"Tamaño de la entrada: {parametros[index+1].size()}")
        del getattr(red_A1,capa).weight
        del getattr(red_A1,capa).bias
        getattr(red_A1,capa).weight = nn.Parameter(parametros[index])
        getattr(red_A1,capa).bias = nn.Parameter(parametros[index+1])
        index = index + 2
    # print(layer(_input))
    # print(torch.zeros(len(_input),dtype=torch.long))
    return criterion(red_A1(_input), torch.zeros_like(red_A1(_input)))

w1 = torch.rand_like(red_A1.fc1.weight)
b1 = torch.rand_like(red_A1.fc1.bias)
w2 = torch.rand_like(red_A1.fc2.weight)
b2 = torch.rand_like(red_A1.fc2.bias)
w3 = torch.rand_like(red_A1.fc3.weight)
b3 = torch.rand_like(red_A1.fc3.bias)
#print([_.view(-1) for _ in red_A1.parameters()])
# h = torch.autograd.functional.hessian(func,(w1,b1,w2,b2,w3,b3))

print( torch.cat([_.view(-1) for _ in red_A1.parameters()], dim = 0))
#print(h)

# def calcula_perdida(*parametros):
#     red_A1 = NARNN(parametros, input_dim=8, hidden_dim=0, output_dim=1, num_layers=0)
#     loss = criterion(red_A1(torch.tensor([1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0])),torch.tensor([1]))#devuelve la perdida
#     return loss

# print(torch.autograd.functional.hessian(calcula_perdida, tuple([_ for _ in red_A1.parameters()])))

_input=torch.randn(10)
# layer = nn.Linear(3,4)
# criterion=nn.MSELoss()

# weight = layer.weight

# class MiRed(nn.Module):
#     def __init__(self):
#         super(MiRed, self).__init__()
#         self.capa1 = nn.Linear(10, 5)
#         self.capa2 = nn.Linear(5, 1)

#     def forward(self, x):
#         tan_sigmoid = lambda a : F.tanh(F.sigmoid(a))
#         x = tan_sigmoid(self.capa1(x))
#         #print(y)
#         #x = torch.sigmoid(self.fc1(x))
#         #print(x)
#         x = F.logsigmoid(self.capa2(x))
#         return x

# mi_red = MiRed()
# weight = torch.rand_like(mi_red.capa1.weight)
# bias = torch.rand_like(mi_red.capa1.bias)
# # Acceso directo a los parámetros usando índices explícitos
# # parametros_capa1_peso = mi_red.capa1.weight
# # parametros_capa1_bias = mi_red.capa1.bias
# #print(weight)

# def func(we,bi):
#     del mi_red.capa1.weight
#     del mi_red.capa1.bias
#     mi_red.capa1.weight= we
#     mi_red.capa1.bias = bi
#     # print(layer(_input))
#     # print(torch.zeros(len(_input),dtype=torch.long))
#     return criterion(mi_red(_input), torch.zeros_like(mi_red(_input)))

# print(torch.autograd.functional.hessian(func,(weight,bias)))

tensor([ 0.3384,  0.2245, -0.3456, -0.2011, -0.0845,  0.3404,  0.2995,  0.2228,
         0.3243, -0.1317, -0.1050,  0.1609,  0.0890, -0.0844,  0.1337,  0.3063,
        -0.1552,  0.0420, -0.1662,  0.0392,  0.1885, -0.2366, -0.3159,  0.3315,
         0.3000, -0.1660, -0.3179,  0.2154, -0.0440, -0.2754,  0.0224, -0.1549,
        -0.3078, -0.1693, -0.2773, -0.1126, -0.3223, -0.0353, -0.2978, -0.2196,
        -0.2321, -0.0659, -0.2351,  0.0627, -0.0241,  0.1985, -0.2821, -0.0762,
        -0.3456, -0.0008, -0.2789, -0.3094, -0.0439,  0.2646, -0.2771,  0.0282,
        -0.0918,  0.1136, -0.0824, -0.0621,  0.1819, -0.0361, -0.3385,  0.1276,
         0.0392, -0.0365,  0.3273,  0.0628, -0.2072, -0.1392, -0.2651,  0.1502,
         0.1415, -0.3427, -0.1770, -0.1052, -0.1880, -0.0107, -0.3439,  0.0895,
         0.1800, -0.2447,  0.2382,  0.2502, -0.0451, -0.2995, -0.2923, -0.1688,
        -0.0310, -0.2394, -0.2822, -0.1251,  0.1031,  0.0825, -0.0620, -0.0859,
        -0.0413, -0.2790, -0.0023,  0.09

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class NARNN(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim, num_layers):
        super(NARNN, self).__init__()
        self.fc1 = nn.Linear(input_dim,10)
        self.fc2 = nn.Linear(10,10)
        self.fc3 = nn.Linear(10,output_dim)

    def forward(self, x):
        tan_sigmoid = lambda a : F.tanh(F.sigmoid(a))
        x = tan_sigmoid(self.fc1(x))
        x = F.logsigmoid(self.fc2(x))
        x = self.fc3(x)
        return x

criterion = nn.MSELoss()
red_A1 = NARNN(input_dim=8, hidden_dim=0, output_dim=1, num_layers=0)

# def calcula_perdida(*parametros):
#        for parametro, entrada in zip(red_A1.parameters(),parametros):
#               parametro.data = entrada
#        loss = criterion(red_A1(torch.tensor([1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0])),torch.tensor([1]))#devuelve la perdida
#        return loss

# def calcula_perdida(*parametros):
#     for i, parametro in enumerate(red_A1.parameters()):
#         parametro = nn.Parameter(parametros[i])
#     loss = criterion(red_A1(torch.tensor([1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0])),torch.tensor([1]))#devuelve la perdida
#     return loss

# def calcula_perdida(*parametros):
#     with torch.no_grad():
#         for i, parametro in enumerate(red_A1.parameters()):
#             parametro.data = parametros[i].data
#     loss = criterion(red_A1(torch.tensor([1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0])),torch.tensor([1]))#devuelve la perdida
#     return loss

def calcula_perdida(*parametros):
    with torch.no_grad():
        for p, nuevo_p in zip(red_A1.parameters(), parametros):
            p.copy_(nuevo_p)
    loss = criterion(red_A1(torch.tensor([1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0])),torch.tensor([1]))#devuelve la perdida
    return loss

print(torch.autograd.functional.hessian(calcula_perdida, tuple([_ for _ in red_A1.parameters()])))

# e = []
# for p in red_A1.parameters():
#        e.append(torch.rand_like(p.data)) 

# #tuple()
# #print(red_A1(torch.tensor([1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0])))
# a = [p.data for p in red_A1.parameters()]
#print(calcula_perdida(a[0],a[1],a[2],a[3],a[4],a[5]))

#print()
#print(tuple([_.view(-1) for _ in red_A1.parameters()]))
#print(tuple([_.view(-1) for _ in red_A1.parameters()]))

In [ ]:
import torch

from torch.autograd import Variable


class NARNN(nn.Module):

    def __init__(self, input_dim, hidden_dim, output_dim, num_layers):

        super(NARNN, self).__init__()

        self.fc1 = nn.Linear(input_dim,10)

        self.fc2 = nn.Linear(10,10)

        self.fc3 = nn.Linear(10,output_dim)


    def forward(self, x):

        tan_sigmoid = lambda a : F.tanh(F.sigmoid(a))

        x = tan_sigmoid(self.fc1(x))

        x = F.logsigmoid(self.fc2(x))

        x = self.fc3(x)

        return x


def calculate_hessian(model, inputs, outputs, criterion):

    # The loss and its gradients w.r.t. the parameters need to be computed.

    loss = criterion(outputs, inputs)

    loss.backward()


    # This vector will store the gradient of the loss w.r.t. each parameter.

    grads = []

    for param in model.parameters():

        grads.append(param.grad.clone().detach().view(-1))


    # This vector will store the diagonal elements of the Hessian matrix.

    hessian_diag = []

    for i, param in enumerate(model.parameters()):

        h = torch.zeros(param.numel(), param.numel())

        grad_ii = grads[i][:, None] # Vector i at position i.

        grad_jj = grads[i][None, :] # Vector i at position j.

        h.as_strided(grad_ii.size(), (h.stride(0), h.stride(1) + h.size(1))).copy_(grad_ii)

        h.as_strided(grad_jj.size(), (h.stride(0) + h.size(0), h.stride(1))).copy_(grad_jj)

        hessian_diag.append(h.detach())


    return hessian_diag


# Initialize the model and criterion

model = NARNN(input_dim=8, hidden_dim=0, output_dim=1, num_layers=0)

criterion = nn.MSELoss()


# Calculate the hessian

hessian = calculate_hessian(model, torch.tensor([1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0]), torch.tensor([1]), criterion)

print(hessian)

In [ ]:
print(tuple([_.data for _ in red_A1.parameters()]))

In [ ]:
import matplotlib.pyplot as plt

# Datos para los gráficos
x1 = [1, 2, 3, 4, 5]
y1 = [10, 15, 7, 12, 9]

x2 = [1, 2, 3, 4, 5]
y2 = [5, 8, 12, 6, 10]

x3 = [1, 2, 3, 4, 5]
y3 = [9, 12, 6, 10, 8]

x4 = [1, 2, 3, 4, 5]
y4 = [8, 7, 5, 11, 14]

x5 = [1, 2, 3, 4, 5]
y5 = [6, 9, 11, 15, 12]

x6 = [1, 2, 3, 4, 5]
y6 = [13, 10, 14, 8, 5]

# Crear una figura con 2 filas y 3 columnas de subtramas
plt.figure(figsize=(12, 8))  # Ajusta el tamaño de la figura

# Subtrama 1
plt.subplot(2, 3, 1)
plt.plot(x1, y1)
plt.title('Gráfico 1')

# Subtrama 2
plt.subplot(2, 3, 2)
plt.plot(x2, y2)
plt.title('Gráfico 2')

# Subtrama 3
plt.subplot(2, 3, 3)
plt.plot(x3, y3)
plt.title('Gráfico 3')

# Subtrama 4
plt.subplot(2, 3, 4)
plt.plot(x4, y4)
plt.title('Gráfico 4')

# Subtrama 5
plt.subplot(2, 3, 5)
plt.plot(x5, y5)
plt.title('Gráfico 5')

# Subtrama 6
plt.subplot(2, 3, 6)
plt.plot(x6, y6)
plt.title('Gráfico 6')

# Ajusta el espacio entre las subtramas para evitar superposiciones
plt.tight_layout()

plt.show()


In [ ]:
for p in red_A1.parameters():
    print("param: " + str(p.data))

In [ ]:
def my_MSEloss(params):
    c = 0
    for param in red_A1.parameters():
        param = params[c]
        print(param)
        c = c + 1

for j in red_A1.parameters():
    print(j)

my_MSEloss([torch.zeros_like(tensor) for tensor in red_A1.parameters()])
#for i in red_A1.parameters():
 #   print(i)

In [ ]:
print(red_A1.parameters)

In [ ]:
print(torch.rand(2, 2))

for i in torch.rand(2, 2):
    print(i)
    print(type(i))


In [ ]:
import torch

class Net(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.a = torch.nn.Parameter(torch.tensor([1.0, -1.0, 2.0]))
        self.b = torch.nn.Parameter(torch.tensor([2.0, -2.0, -1.0]))

    def forward(self, x):
        output = (x * self.a.unsqueeze(0) ** 3 + x * self.b.unsqueeze(0) ** 3).sum(dim=1)
        return output

x = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
y = torch.tensor([1.0, 2.0])
net = Net()

def compute_z(*net_parameters):
    # Is there a proper way to set the parameters that works with hessian?
    for p_src, p_dst in zip(net_parameters, net.parameters()):
        p_dst.data = p_src.data

    output = net(x)
    z = ((output - y)**2).mean()
    return z

# strict=True raises exception, allowing non-strict for demonstration
hessians = torch.autograd.functional.hessian(compute_z, tuple(net.parameters()))

param_names = [n for n, _ in net.named_parameters()]
for d_name, d_hessians in zip(param_names, hessians):
    for dd_name, dd_hessian in zip(param_names, d_hessians):
        print(f'dz/d{dd_name}d{d_name} = \n{dd_hessian}\n')

In [ ]:
#optimizer = optim.SGD(red.parameters(), lr=0.1, momentum=0.4)#,maximize=True)
#optimizer.zero_grad()
output = red_A1(torch.Tensor([1,2,3,4,5,6,7,8]))
target = torch.Tensor([1,2,3,4,5,6,7,8])
loss = criterion(output, target)
print(loss)
print(type(criterion))
print(type(loss.grad_fn))

print(output)
print(type(output.grad_fn))

t = []

for c in red_A1.parameters():
    print(type(c.data))
    t.append(c.data)

#torch.cat(,dim = 0)
# print(t)

h = torch.autograd.functional.hessian(loss.grad_fn, torch.rand(2, 2))

In [ ]:




print(loss)
loss.backward()
h = torch.autograd.functional.hessian(loss)#calcula el hessiana de la funcion de perdida
h+ lambda 
print(loss.backward())
optimizer.step()

In [ ]:
criterion = nn.MSELoss()