In [1]:
import torch
import numpy as np
from torch.nn import Module
import torch.nn as nn
import torch.nn.functional as F
from NARNN import NARNN

from levenberg_marquardt import LM

red = NARNN(input_dim=8, hidden_dim=0, output_dim=1, num_layers=0)
#input = torch.Tensor([1,2,3,4,5,6,7,8])

# print(input)
entrada = input #la entrada se da como un parametro global
salida_esperada = torch.tensor([-0.0834]) #lo mismo para la salida esperada
# λ = 0.1



print(red(torch.Tensor([1,2,3,4,5,6,7,8])))


tensor([0.4884], grad_fn=<AddBackward0>)


/home/miguel/anaconda3/lib/python3.9/site-packages/torch/nn/functional.py:1944: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
/home/miguel/anaconda3/lib/python3.9/site-packages/torch/nn/functional.py:1933: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")


In [2]:
print("Antes")
print([i for i in red.parameters()])
print(red(torch.Tensor([1,2,3,4,5,6,7,8])))

Antes
[Parameter containing:
tensor([[-0.0797,  0.0073, -0.0598,  0.1786, -0.2524,  0.0537,  0.2277, -0.1192],
        [-0.1985,  0.2473,  0.0691, -0.0271,  0.1058,  0.0982, -0.1964, -0.1613],
        [ 0.0789,  0.1483, -0.1321, -0.0894,  0.2940, -0.2954,  0.1811,  0.2621],
        [-0.2028,  0.2626, -0.1991, -0.2144,  0.2224,  0.2139,  0.2694,  0.1281],
        [ 0.0284, -0.0204,  0.1192,  0.2104, -0.0191, -0.0847, -0.3487, -0.2058],
        [ 0.0412,  0.2255,  0.2777, -0.3318, -0.2635, -0.2094, -0.3100, -0.2829],
        [-0.3337, -0.2234,  0.1577,  0.3484, -0.1335, -0.0568, -0.1739,  0.2567],
        [ 0.1404, -0.0089, -0.1057, -0.1257, -0.2342, -0.0408,  0.3042, -0.0711],
        [-0.1237, -0.0345, -0.2599,  0.1833,  0.1387, -0.2969, -0.0318, -0.2513],
        [-0.1788,  0.1941,  0.3322,  0.3085, -0.2480, -0.0149,  0.1150, -0.0085]],
       requires_grad=True), Parameter containing:
tensor([ 0.2034,  0.2809, -0.0021, -0.1663, -0.3272,  0.1422,  0.2390, -0.1130,
        -0.1114, -0.

In [5]:

#print(red(torch.Tensor([1,2,3,4,5,6,7,8])))
lm = LM(red, torch.Tensor([0.0574, 0.0526, 0.0532, 0.0526, 0.0574, 0.0446, 0.0259, 0.0728]),torch.tensor([0.0675]))
lm.exec()
print("Despues")
#print(red(torch.Tensor([1,2,3,4,5,6,7,8])))

aux_convierte_parametros
asigna parametros


RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x1 and 8x10)

In [4]:
print("Despues")
print([i for i in red.parameters()])
print(red(torch.Tensor([1,2,3,4,5,6,7,8])))

Despues
[Parameter containing:
tensor([[-0.0797,  0.0073, -0.0598,  0.1786, -0.2524,  0.0537,  0.2276, -0.1193],
        [-0.1984,  0.2474,  0.0693, -0.0269,  0.1061,  0.0985, -0.1960, -0.1609],
        [ 0.0788,  0.1481, -0.1325, -0.0899,  0.2934, -0.2962,  0.1803,  0.2611],
        [-0.2030,  0.2622, -0.1998, -0.2153,  0.2213,  0.2126,  0.2678,  0.1263],
        [ 0.0286, -0.0200,  0.1199,  0.2112, -0.0180, -0.0834, -0.3471, -0.2041],
        [ 0.0417,  0.2263,  0.2790, -0.3301, -0.2614, -0.2069, -0.3070, -0.2795],
        [-0.3338, -0.2235,  0.1576,  0.3482, -0.1338, -0.0571, -0.1743,  0.2563],
        [ 0.1405, -0.0088, -0.1055, -0.1255, -0.2339, -0.0405,  0.3046, -0.0706],
        [-0.1235, -0.0341, -0.2593,  0.1842,  0.1397, -0.2956, -0.0304, -0.2496],
        [-0.1789,  0.1938,  0.3318,  0.3079, -0.2487, -0.0158,  0.1140, -0.0096]],
       requires_grad=True), Parameter containing:
tensor([ 0.2034,  0.2810, -0.0023, -0.1665, -0.3270,  0.1427,  0.2389, -0.1129,
        -0.1112, -

In [ ]:




class Net(Module):
    def __init__(self, h, w):
        super(Net, self).__init__()
        self.c1 = torch.nn.Conv2d(1, 32, 3, 1, 1)
        self.f2 = torch.nn.Linear(32 * h * w, 5)

    def forward(self, x):
        x = self.c1(x)
        x = x.view(x.size(0), -1)
        x = self.f2(x)
        return x

class NARNN(Module):
    def __init__(self, input_dim, hidden_dim, output_dim, num_layers):
        super(NARNN, self).__init__()
        #self.hidden_dim = hidden_dim
        #self.num_layers = num_layers
        #self.lstm = nn.LSTM(input_dim, hidden_dim, num_layers, batch_first=True)#capa lstm
        #self.fc1 = nn.Linear(hidden_dim, output_dim)#capa lineal
        self.fc1 = nn.Linear(input_dim,10)
        self.fc2 = nn.Linear(10,10)
        self.fc3 = nn.Linear(10,output_dim)

    def forward(self, x):
        """h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_dim).requires_grad_()#Crea tensores con las dimensiones especificadas
        c0 = torch.zeros(self.num_layers, x.size(0), self.hidden_dim).requires_grad_()

        out, _ = self.lstm(x, (h0.detach(), c0.detach()))

        out = self.fc1(out[:, -1, :]) 
        return out"""
        tan_sigmoid = lambda a : F.tanh(F.sigmoid(a))
        x = tan_sigmoid(self.fc1(x))
        #print(y)
        #x = torch.sigmoid(self.fc1(x))
        #print(x)
        x = F.logsigmoid(self.fc2(x))
        x = self.fc3(x)
        return x
    
def fun(a, b, c, d):
    p = [a.view(32, 1, 3, 3), b, c.view(5, 32 * 12 * 12), d]
    x = torch.randn(size=[8, 1, 12, 12], dtype=torch.float32)
    y = torch.randint(0, 5, [8])
    x = F.conv2d(x, p[0], p[1], 1, 1)
    x = x.view(x.size(0), -1)
    x = F.linear(x, p[2], p[3])
    loss = F.cross_entropy(x, y)
    return loss

red = NARNN(input_dim=8, hidden_dim=0, output_dim=1, num_layers=0)
input = torch.Tensor([1,2,3,4,5,6,7,8])

print(input)
entrada = input #la entrada se da como un parametro global
salida_esperada = torch.tensor([-0.0834]) #lo mismo para la salida esperada
λ = 0.1

# def calcula_perdida(*parametros):
#     #red.fc1.weight.data = 
#     params = []
#     i=0
#     for param in parametros:
#         params.append(param)
#         #print(param)
#     for r_param in red.parameters():
#         params[i].view(r_param.shape)#se le da la forma del parametro correspondiente a los parametros que llegan como entrada
#         r_param = params[i]
#         i = i+1
#     #print([b for b in red.parameters()])
#     salida = red(entrada)
#     criterion = nn.MSELoss()
#     return criterion(salida,salida_esperada)

# def calcula_perdida(*parametros):
#     #red.fc1.weight.data = 
#     params = []
#     i=0
#     #parametros = list(parametros)
#     for param in parametros:
#         params.append(param)
#         print(param)
#     for r_param in red.parameters():
#         params[i] = params[i].view(r_param.shape)#se le da la forma del parametro correspondiente a los parametros que llegan como entrada
#         # r_param = params[i]
#         i = i+1
#     #print([b for b in red.parameters()]
#     l1 = F.linear(entrada,params[0],params[1])
#     #print(params[0])
#     #print(params[1])
#     #print("Entradal1: " + str(l1))
#     l2 = F.linear(l1,params[2],params[3])
#     #print("Entradal2: " + str(l2))
#     salida = F.linear(l2,params[4],params[5])
#     #print("Salida: " + str(salida))

#     #salida = (entrada)
#     criterion = nn.MSELoss()
#     return criterion(salida,salida_esperada)

def calcula_perdida(*parametros):
    #red.fc1.weight.data = 
    params = []
    n_params = []
    i=0
    n_dim = 0
    #parametros = list(parametros)
    for param in parametros:
        params.append(param)#recibiria un solo tensor con todos los pesos
    for r_param in red.parameters():
        p_partida = n_dim
        print("shape: " + str(r_param.shape))
        n_dim = r_param.size(0)*(r_param.size(1) if r_param.dim() == 2 else 1) + p_partida#se obtiene la dimension del primer conjunto de pparametros de la red
        print("n_dim: " + str(n_dim) + " p_partida: " + str(p_partida))
        #print("primer vector: " + str(params[0][p_partida:n_dim]))
        n_params.append(params[0][p_partida:n_dim])
        print("primer vector: " + str(n_params[i]))
        n_params[i] = n_params[i].view(r_param.shape)#se le da la forma del parametro correspondiente a los parametros que llegan como entrada
        print("segundo vector: " + str(n_params[i]))
        i = i+1
    #print([b for b in red.parameters()]
    l1 = F.linear(entrada,n_params[0],n_params[1])
    #print(params[0])
    #print(params[1])
    #print("Entradal1: " + str(l1))
    l2 = F.linear(l1,n_params[2],n_params[3])
    #print("Entradal2: " + str(l2))
    salida = F.linear(l2,n_params[4],n_params[5])
    #print("Salida: " + str(salida))

    #salida = (entrada)
    criterion = nn.MSELoss()
    return criterion(salida,salida_esperada)


#print([b for b in red.parameters()])


In [ ]:
#torch.rand(2,2)
a= torch.tensor([1,2,3,4,5,6,7,8,9,10])
print(a.dim())
print(torch.rand(2,5))
print(a.view(2,5))
def pow_reducer(x):
    return x.pow(3).sum()
inputs = torch.rand(10)
print(inputs.dim())
print(torch.autograd.functional.hessian(pow_reducer, inputs))


In [ ]:
entrada = input
#print(red.fc1.weight.data)
#red.fc1.weight.data = torch.zeros((10,8))
#print(red.fc1.weight.data)
#print(torch.tensor([[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8]]))
#print(red.fc2.weight.data)
#print(red.fc3.weight.data)
v = [_.view(-1) for _ in red.parameters()]
#for i in v:
 #   print(i)
v = torch.cat([_.view(-1) for _ in red.parameters()], dim = 0)#concatena los paremetros de la red en un solo vector unidimensional
#print(v)
p = calcula_perdida(v)
#print(len(v))
#p = calcula_perdida(v[0],v[1],v[2],v[3],v[4],v[5])
#print(red(entrada))
print(p)

In [ ]:
print(v.dim())
# class Net(Module):
#     def __init__(self, h, w):
#         super(Net, self).__init__()
#         self.c1 = torch.nn.Conv2d(1, 32, 3, 1, 1)
#         self.f2 = torch.nn.Linear(32 * h * w, 5)


#     def forward(self, x):
#         x = self.c1(x)
#         x = x.view(x.size(0), -1)
#         x = self.f2(x)
#         return x

# def haha(a, b, c, d):
#     p = [a.view(32, 1, 3, 3), b, c.view(5, 32 * 12 * 12), d]
#     x = torch.randn(size=[8, 1, 12, 12], dtype=torch.float32)
#     y = torch.randint(0, 5, [8])
#     x = F.conv2d(x, p[0], p[1], 1, 1)
#     x = x.view(x.size(0), -1)
#     x = F.linear(x, p[2], p[3])
#     loss = F.cross_entropy(x, y)
#     return loss
h = torch.autograd.functional.hessian(calcula_perdida, v)
#print(len(list(a)))
#print(len(list(a)[0]))
print(h.dim())
print(h.shape)

#print(h = torch.autograd.functional.hessian(haha, tuple([_.view(-1) for _ in net.parameters()])))

In [ ]:
grad_f = torch.autograd.grad(calcula_perdida(v), v)[0]
print(grad_f.shape)

In [ ]:
λ = 0.1
r = torch.matmul((-torch.inverse(h+λ*torch.eye(211))),torch.transpose(torch.unsqueeze(grad_f, 0),0, 1))
print(r)
print(torch.transpose(r,0,1))
#-torch.inverse(h+λ*torch.eye(211))

In [ ]:
print(r)
#print(torch.transpose(torch.unsqueeze(grad_f, 0),0, 1).shape)

#print(-(0.1*torch.eye(211)+torch.eye(211)))
#print([_.view(-1) for _ in red.parameters()])

In [ ]:

x = torch.randn(1,80)
print(x)
y = []
for i in red.parameters():
    y.append(i.shape)
#x = x.view(y[0])
print(x.view(y[0]))


In [ ]:
# Supongamos que tienes dos tensores con diferentes formas
tensor_existente = torch.tensor([[1, 2, 3], [4, 5, 6]])
otro_tensor = torch.tensor([[7, 8], [9, 10],[11,12]])

# Obtén la forma del otro tensor
forma_deseada = otro_tensor.shape

# Ajusta la forma del tensor existente para que coincida con la forma deseada
tensor_ajustado = tensor_existente.view(forma_deseada)

# Alternativamente, puedes usar reshape
# tensor_ajustado = tensor_existente.reshape(forma_deseada)

print("Tensor existente:")
print(tensor_existente)

print("Tensor ajustado con la misma forma que el otro tensor:")
print(tensor_ajustado)

In [ ]:
def pow_reducer(x):
    x=x.view(-1)
    return x.pow(3).sum()
inputs = torch.Tensor([[2,4],[1,3]])
print(inputs)
torch.autograd.functional.hessian(pow_reducer, inputs)

In [ ]:
print(torch.Tensor([[2,4],[1,3]]))
print(torch.Tensor([[2,4],[1,3]]).view(-1))


In [ ]:
def pow_r(x):
    return x.pow(3).sum()

print(pow_r(torch.Tensor([2])))

In [ ]:
net = Net(12, 12)

print([i.view(-1) for i in net.parameters()][0].size())
print([i for i in net.parameters()][0].size())

t = tuple([_.view(-1) for _ in net.parameters()])

print(torch.randn(size=[8, 1, 12, 12], dtype=torch.float32))
#print(net)
#print(len(t))

In [ ]:

#h = torch.autograd.functional.hessian(haha, tuple([_.view(-1) for _ in net.parameters()]))
tuple([_.view(-1) for _ in net.parameters()])

In [ ]:


# v = torch.cat([_.view(-1) for _ in red.parameters()], dim = 0)#concatena los paremetros de la red en un solo vector unidimensional
# h = torch.autograd.functional.hessian(lm.calcula_perdida, v) #calculamos la matriz hessiana
# grad_f = torch.autograd.grad(lm.calcula_perdida(v), v)[0] #calculamos el gradiente de la funcion
# r = -torch.inverse(h+λ*torch.eye(211))*torch.transpose(grad_f)
