In [25]:
import torch
import numpy as np
from torch.nn import Module
import torch.nn as nn
import torch.nn.functional as F

class Net(Module):
    def __init__(self, h, w):
        super(Net, self).__init__()
        self.c1 = torch.nn.Conv2d(1, 32, 3, 1, 1)
        self.f2 = torch.nn.Linear(32 * h * w, 5)

    def forward(self, x):
        x = self.c1(x)
        x = x.view(x.size(0), -1)
        x = self.f2(x)
        return x

class NARNN(Module):
    def __init__(self, input_dim, hidden_dim, output_dim, num_layers):
        super(NARNN, self).__init__()
        #self.hidden_dim = hidden_dim
        #self.num_layers = num_layers
        #self.lstm = nn.LSTM(input_dim, hidden_dim, num_layers, batch_first=True)#capa lstm
        #self.fc1 = nn.Linear(hidden_dim, output_dim)#capa lineal
        self.fc1 = nn.Linear(input_dim,10)
        self.fc2 = nn.Linear(10,10)
        self.fc3 = nn.Linear(10,output_dim)

    def forward(self, x):
        """h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_dim).requires_grad_()#Crea tensores con las dimensiones especificadas
        c0 = torch.zeros(self.num_layers, x.size(0), self.hidden_dim).requires_grad_()

        out, _ = self.lstm(x, (h0.detach(), c0.detach()))

        out = self.fc1(out[:, -1, :]) 
        return out"""
        tan_sigmoid = lambda a : F.tanh(F.sigmoid(a))
        x = tan_sigmoid(self.fc1(x))
        #print(y)
        #x = torch.sigmoid(self.fc1(x))
        #print(x)
        x = F.logsigmoid(self.fc2(x))
        x = self.fc3(x)
        return x
    
def fun(a, b, c, d):
    p = [a.view(32, 1, 3, 3), b, c.view(5, 32 * 12 * 12), d]
    x = torch.randn(size=[8, 1, 12, 12], dtype=torch.float32)
    y = torch.randint(0, 5, [8])
    x = F.conv2d(x, p[0], p[1], 1, 1)
    x = x.view(x.size(0), -1)
    x = F.linear(x, p[2], p[3])
    loss = F.cross_entropy(x, y)
    return loss

red = NARNN(input_dim=8, hidden_dim=0, output_dim=1, num_layers=0)
input = torch.Tensor([1,2,3,4,5,6,7,8])

print(input)
entrada = input #la entrada se da como un parametro global
salida_esperada = torch.tensor([-0.0834]) #lo mismo para la salida esperada

# def calcula_perdida(*parametros):
#     #red.fc1.weight.data = 
#     params = []
#     i=0
#     for param in parametros:
#         params.append(param)
#         #print(param)
#     for r_param in red.parameters():
#         params[i].view(r_param.shape)#se le da la forma del parametro correspondiente a los parametros que llegan como entrada
#         r_param = params[i]
#         i = i+1
#     #print([b for b in red.parameters()])
#     salida = red(entrada)
#     criterion = nn.MSELoss()
#     return criterion(salida,salida_esperada)

# def calcula_perdida(*parametros):
#     #red.fc1.weight.data = 
#     params = []
#     i=0
#     #parametros = list(parametros)
#     for param in parametros:
#         params.append(param)
#         print(param)
#     for r_param in red.parameters():
#         params[i] = params[i].view(r_param.shape)#se le da la forma del parametro correspondiente a los parametros que llegan como entrada
#         # r_param = params[i]
#         i = i+1
#     #print([b for b in red.parameters()]
#     l1 = F.linear(entrada,params[0],params[1])
#     #print(params[0])
#     #print(params[1])
#     #print("Entradal1: " + str(l1))
#     l2 = F.linear(l1,params[2],params[3])
#     #print("Entradal2: " + str(l2))
#     salida = F.linear(l2,params[4],params[5])
#     #print("Salida: " + str(salida))

#     #salida = (entrada)
#     criterion = nn.MSELoss()
#     return criterion(salida,salida_esperada)

def calcula_perdida(*parametros):
    #red.fc1.weight.data = 
    params = []
    n_params = []
    i=0
    n_dim = 0
    #parametros = list(parametros)
    for param in parametros:
        params.append(param)#recibiria un solo tensor con todos los pesos
    for r_param in red.parameters():
        p_partida = n_dim+1
        n_dim = r_param.size(0)*r_param.size(1) #se obtiene la dimension del primer conjunto de pparametros de la red
        n_params[i] = params[0][:n_dim, :]
        n_params[i] = n_params[i].view(r_param.shape)#se le da la forma del parametro correspondiente a los parametros que llegan como entrada
        i = i+1
    #print([b for b in red.parameters()]
    l1 = F.linear(entrada,params[0],params[1])
    #print(params[0])
    #print(params[1])
    #print("Entradal1: " + str(l1))
    l2 = F.linear(l1,params[2],params[3])
    #print("Entradal2: " + str(l2))
    salida = F.linear(l2,params[4],params[5])
    #print("Salida: " + str(salida))

    #salida = (entrada)
    criterion = nn.MSELoss()
    return criterion(salida,salida_esperada)


#print([b for b in red.parameters()])


tensor([1., 2., 3., 4., 5., 6., 7., 8.])


In [42]:
#torch.rand(2,2)
a= torch.tensor([1,2,3,4,5,6,7,8,9,10])
print(a.shape)
print(a[0:1, :])


torch.Size([10])


IndexError: too many indices for tensor of dimension 1

In [26]:
entrada = input
#print(red.fc1.weight.data)
#red.fc1.weight.data = torch.zeros((10,8))
#print(red.fc1.weight.data)
#print(torch.tensor([[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8]]))
#print(red.fc2.weight.data)
#print(red.fc3.weight.data)
v = [_.view(-1) for _ in red.parameters()]
#print(len(v))
p = calcula_perdida(v[0],v[1],v[2],v[3],v[4],v[5])
#print(red(entrada))
print(p)

tensor([ 1.2304e-01, -1.9184e-01,  1.8802e-01,  1.4832e-01,  3.0044e-01,
         9.6537e-04, -1.3341e-02,  1.0219e-01,  9.6924e-02, -2.7140e-01,
        -1.9343e-02, -2.2502e-02, -3.2963e-01, -1.8602e-01,  2.3739e-01,
         2.3699e-01,  1.4987e-01,  1.6612e-01, -1.4459e-01, -8.7238e-02,
         8.9779e-03,  2.6686e-01,  3.2407e-01,  1.3229e-01, -1.8551e-01,
         1.3540e-01,  1.8300e-01, -9.3619e-02, -5.3804e-02,  9.5736e-02,
        -3.0604e-01, -1.2713e-01, -1.2728e-05,  6.8656e-03, -1.7085e-01,
         1.8625e-01, -2.6061e-01, -1.1374e-01,  1.8544e-01,  1.1566e-01,
         5.2061e-02,  3.1409e-01,  1.7003e-02,  2.7665e-01, -7.6043e-02,
        -3.3319e-01,  9.3892e-02, -2.7791e-01, -3.5025e-01, -2.7077e-01,
         2.3597e-01, -1.9512e-01,  3.2122e-02, -1.6492e-01,  1.6434e-01,
         2.5835e-01, -3.3324e-01, -6.4340e-02,  3.2720e-01,  4.1475e-02,
         1.4370e-01,  2.7603e-01,  1.3086e-01, -2.3386e-01, -1.8583e-01,
         2.4805e-01, -1.7643e-01, -3.3655e-01,  1.6

In [28]:

# class Net(Module):
#     def __init__(self, h, w):
#         super(Net, self).__init__()
#         self.c1 = torch.nn.Conv2d(1, 32, 3, 1, 1)
#         self.f2 = torch.nn.Linear(32 * h * w, 5)

#     def forward(self, x):
#         x = self.c1(x)
#         x = x.view(x.size(0), -1)
#         x = self.f2(x)
#         return x

# def haha(a, b, c, d):
#     p = [a.view(32, 1, 3, 3), b, c.view(5, 32 * 12 * 12), d]
#     x = torch.randn(size=[8, 1, 12, 12], dtype=torch.float32)
#     y = torch.randint(0, 5, [8])
#     x = F.conv2d(x, p[0], p[1], 1, 1)
#     x = x.view(x.size(0), -1)
#     x = F.linear(x, p[2], p[3])
#     loss = F.cross_entropy(x, y)
#     return loss
a = torch.autograd.functional.hessian(calcula_perdida, tuple(v))
#print(len(list(a)))
print(len(list(a)[0]))
#print(h = torch.autograd.functional.hessian(haha, tuple([_.view(-1) for _ in net.parameters()])))

tensor([ 1.2304e-01, -1.9184e-01,  1.8802e-01,  1.4832e-01,  3.0044e-01,
         9.6537e-04, -1.3341e-02,  1.0219e-01,  9.6924e-02, -2.7140e-01,
        -1.9343e-02, -2.2502e-02, -3.2963e-01, -1.8602e-01,  2.3739e-01,
         2.3699e-01,  1.4987e-01,  1.6612e-01, -1.4459e-01, -8.7238e-02,
         8.9779e-03,  2.6686e-01,  3.2407e-01,  1.3229e-01, -1.8551e-01,
         1.3540e-01,  1.8300e-01, -9.3619e-02, -5.3804e-02,  9.5736e-02,
        -3.0604e-01, -1.2713e-01, -1.2728e-05,  6.8656e-03, -1.7085e-01,
         1.8625e-01, -2.6061e-01, -1.1374e-01,  1.8544e-01,  1.1566e-01,
         5.2061e-02,  3.1409e-01,  1.7003e-02,  2.7665e-01, -7.6043e-02,
        -3.3319e-01,  9.3892e-02, -2.7791e-01, -3.5025e-01, -2.7077e-01,
         2.3597e-01, -1.9512e-01,  3.2122e-02, -1.6492e-01,  1.6434e-01,
         2.5835e-01, -3.3324e-01, -6.4340e-02,  3.2720e-01,  4.1475e-02,
         1.4370e-01,  2.7603e-01,  1.3086e-01, -2.3386e-01, -1.8583e-01,
         2.4805e-01, -1.7643e-01, -3.3655e-01,  1.6

In [4]:

x = torch.randn(1,80)
print(x)
y = []
for i in red.parameters():
    y.append(i.shape)
#x = x.view(y[0])
print(x.view(y[0]))


tensor([[ 1.2425, -2.0265, -0.7171,  0.8465,  1.1031,  0.8568, -0.5701,  0.4621,
         -1.8919,  1.8212,  0.2178, -0.4279, -0.3306, -2.0242,  0.1793, -0.6342,
          0.5306, -0.3990, -1.4124, -0.0128, -1.2783, -0.7999, -0.9947, -0.0745,
          0.5407,  1.7440, -0.6248,  0.2478,  0.1415,  1.3523, -0.6399, -1.1641,
         -0.7785, -1.3825, -0.1487, -1.1846, -1.9734,  0.9720,  0.8780,  0.1155,
          1.0394,  1.2352,  1.3094,  0.6719, -1.3239, -0.2211, -1.4850, -0.1578,
         -1.3046, -1.6374,  0.7868,  1.4017,  0.0231,  0.7787, -0.9604,  0.5887,
          0.6013, -0.5279,  1.2014,  0.2648, -2.1216, -0.2071,  0.0888, -2.6840,
          0.7722, -0.1971,  1.9545, -0.2919, -0.4544, -0.3679, -1.6071, -0.4358,
          0.1476,  1.1260, -0.7250, -1.1016, -0.7317,  0.0610,  0.5086, -0.1533]])
tensor([[ 1.2425, -2.0265, -0.7171,  0.8465,  1.1031,  0.8568, -0.5701,  0.4621],
        [-1.8919,  1.8212,  0.2178, -0.4279, -0.3306, -2.0242,  0.1793, -0.6342],
        [ 0.5306, -0.399

In [5]:
# Supongamos que tienes dos tensores con diferentes formas
tensor_existente = torch.tensor([[1, 2, 3], [4, 5, 6]])
otro_tensor = torch.tensor([[7, 8], [9, 10],[11,12]])

# Obtén la forma del otro tensor
forma_deseada = otro_tensor.shape

# Ajusta la forma del tensor existente para que coincida con la forma deseada
tensor_ajustado = tensor_existente.view(forma_deseada)

# Alternativamente, puedes usar reshape
# tensor_ajustado = tensor_existente.reshape(forma_deseada)

print("Tensor existente:")
print(tensor_existente)

print("Tensor ajustado con la misma forma que el otro tensor:")
print(tensor_ajustado)

Tensor existente:
tensor([[1, 2, 3],
        [4, 5, 6]])
Tensor ajustado con la misma forma que el otro tensor:
tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [6]:
def pow_reducer(x):
    x=x.view(-1)
    return x.pow(3).sum()
inputs = torch.Tensor([[2,4],[1,3]])
print(inputs)
torch.autograd.functional.hessian(pow_reducer, inputs)

tensor([[2., 4.],
        [1., 3.]])


tensor([[[[12.,  0.],
          [ 0.,  0.]],

         [[ 0., 24.],
          [ 0.,  0.]]],


        [[[ 0.,  0.],
          [ 6.,  0.]],

         [[ 0.,  0.],
          [ 0., 18.]]]])

In [7]:
print(torch.Tensor([[2,4],[1,3]]))
print(torch.Tensor([[2,4],[1,3]]).view(-1))


tensor([[2., 4.],
        [1., 3.]])
tensor([2., 4., 1., 3.])


In [8]:
def pow_r(x):
    return x.pow(3).sum()

print(pow_r(torch.Tensor([2])))

tensor(8.)


In [9]:
net = Net(12, 12)

print([i.view(-1) for i in net.parameters()][0].size())
print([i for i in net.parameters()][0].size())

t = tuple([_.view(-1) for _ in net.parameters()])

print(torch.randn(size=[8, 1, 12, 12], dtype=torch.float32))
#print(net)
#print(len(t))

torch.Size([288])
torch.Size([32, 1, 3, 3])
tensor([[[[ 5.7037e-01, -1.6220e+00,  2.2039e-01,  ..., -1.8979e+00,
           -1.5416e+00, -5.3563e-01],
          [-1.1947e+00,  2.2494e-01,  1.4591e-01,  ...,  4.6369e-01,
           -1.0561e+00, -8.1643e-01],
          [-7.8351e-01, -6.7065e-01,  6.7817e-01,  ...,  2.3470e-01,
            7.0937e-02,  1.5931e+00],
          ...,
          [-7.5470e-01, -1.5926e-01,  5.1093e-01,  ...,  6.1051e-02,
            1.3519e-01,  4.6800e-01],
          [ 2.7908e-01,  7.1455e-01,  2.5397e-01,  ..., -8.8045e-01,
            9.4286e-01,  2.1376e-01],
          [ 2.5175e+00, -4.4433e-01, -2.6354e-01,  ..., -1.1572e+00,
           -1.5571e+00,  9.0103e-01]]],


        [[[-4.0976e-01, -5.2877e-01, -6.8055e-01,  ...,  1.1446e+00,
           -1.6650e-01, -3.5450e-01],
          [-8.4889e-02,  3.4633e-01,  4.9917e-01,  ...,  1.4496e+00,
            3.3475e+00,  1.2317e+00],
          [-4.7402e-01,  5.1185e-01, -5.0354e-01,  ..., -7.3297e-01,
           -

In [10]:

#h = torch.autograd.functional.hessian(haha, tuple([_.view(-1) for _ in net.parameters()]))
tuple([_.view(-1) for _ in net.parameters()])

(tensor([ 0.1217, -0.0818, -0.1036,  0.3002,  0.1637, -0.1048,  0.2623,  0.2988,
         -0.2624,  0.1128, -0.0690,  0.2537,  0.3321, -0.1400,  0.0543,  0.3223,
         -0.0853, -0.0464,  0.0765, -0.0377, -0.2048,  0.3262,  0.0286, -0.0862,
         -0.1481, -0.1255,  0.3250,  0.2934,  0.1509,  0.2734,  0.0445, -0.0381,
         -0.1065,  0.0958,  0.2534,  0.0984,  0.0806,  0.0021,  0.2244, -0.1927,
         -0.1488,  0.0710, -0.0175, -0.1059,  0.1912,  0.2350,  0.1904, -0.0048,
         -0.1818,  0.1958, -0.0474,  0.0634, -0.2812, -0.1592, -0.1451, -0.0265,
         -0.0242, -0.2434, -0.0942,  0.1893,  0.1298, -0.2936,  0.1334, -0.1612,
          0.0079,  0.2406,  0.1352,  0.2592, -0.2827,  0.2473, -0.2747, -0.1128,
         -0.0998,  0.3259,  0.2503,  0.0906, -0.0950, -0.1080,  0.0297,  0.2630,
         -0.2460,  0.1935, -0.1856, -0.0456,  0.2585,  0.1985,  0.0689,  0.0778,
         -0.0363, -0.0353,  0.2892,  0.2555, -0.0505, -0.2110, -0.1705,  0.1030,
          0.2529,  0.0185,  

In [11]:


print(type(h))

NameError: name 'h' is not defined