In [58]:
import torch
import numpy as np
from torch.nn import Module
import torch.nn as nn
import torch.nn.functional as F



class Net(Module):
    def __init__(self, h, w):
        super(Net, self).__init__()
        self.c1 = torch.nn.Conv2d(1, 32, 3, 1, 1)
        self.f2 = torch.nn.Linear(32 * h * w, 5)

    def forward(self, x):
        x = self.c1(x)
        x = x.view(x.size(0), -1)
        x = self.f2(x)
        return x

class NARNN(Module):
    def __init__(self, input_dim, hidden_dim, output_dim, num_layers):
        super(NARNN, self).__init__()
        #self.hidden_dim = hidden_dim
        #self.num_layers = num_layers
        #self.lstm = nn.LSTM(input_dim, hidden_dim, num_layers, batch_first=True)#capa lstm
        #self.fc1 = nn.Linear(hidden_dim, output_dim)#capa lineal
        self.fc1 = nn.Linear(input_dim,10)
        self.fc2 = nn.Linear(10,10)
        self.fc3 = nn.Linear(10,output_dim)

    def forward(self, x):
        """h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_dim).requires_grad_()#Crea tensores con las dimensiones especificadas
        c0 = torch.zeros(self.num_layers, x.size(0), self.hidden_dim).requires_grad_()

        out, _ = self.lstm(x, (h0.detach(), c0.detach()))

        out = self.fc1(out[:, -1, :]) 
        return out"""
        tan_sigmoid = lambda a : F.tanh(F.sigmoid(a))
        x = tan_sigmoid(self.fc1(x))
        #print(y)
        #x = torch.sigmoid(self.fc1(x))
        #print(x)
        x = F.logsigmoid(self.fc2(x))
        x = self.fc3(x)
        return x
    
def fun(a, b, c, d):
    p = [a.view(32, 1, 3, 3), b, c.view(5, 32 * 12 * 12), d]
    x = torch.randn(size=[8, 1, 12, 12], dtype=torch.float32)
    y = torch.randint(0, 5, [8])
    x = F.conv2d(x, p[0], p[1], 1, 1)
    x = x.view(x.size(0), -1)
    x = F.linear(x, p[2], p[3])
    loss = F.cross_entropy(x, y)
    return loss

red = NARNN(input_dim=8, hidden_dim=0, output_dim=1, num_layers=0)
input = torch.Tensor([1,2,3,4,5,6,7,8])

print(input)
entrada = input #la entrada se da como un parametro global
salida_esperada = torch.tensor([-0.0834]) #lo mismo para la salida esperada
λ = 0.1

# def calcula_perdida(*parametros):
#     #red.fc1.weight.data = 
#     params = []
#     i=0
#     for param in parametros:
#         params.append(param)
#         #print(param)
#     for r_param in red.parameters():
#         params[i].view(r_param.shape)#se le da la forma del parametro correspondiente a los parametros que llegan como entrada
#         r_param = params[i]
#         i = i+1
#     #print([b for b in red.parameters()])
#     salida = red(entrada)
#     criterion = nn.MSELoss()
#     return criterion(salida,salida_esperada)

# def calcula_perdida(*parametros):
#     #red.fc1.weight.data = 
#     params = []
#     i=0
#     #parametros = list(parametros)
#     for param in parametros:
#         params.append(param)
#         print(param)
#     for r_param in red.parameters():
#         params[i] = params[i].view(r_param.shape)#se le da la forma del parametro correspondiente a los parametros que llegan como entrada
#         # r_param = params[i]
#         i = i+1
#     #print([b for b in red.parameters()]
#     l1 = F.linear(entrada,params[0],params[1])
#     #print(params[0])
#     #print(params[1])
#     #print("Entradal1: " + str(l1))
#     l2 = F.linear(l1,params[2],params[3])
#     #print("Entradal2: " + str(l2))
#     salida = F.linear(l2,params[4],params[5])
#     #print("Salida: " + str(salida))

#     #salida = (entrada)
#     criterion = nn.MSELoss()
#     return criterion(salida,salida_esperada)

def calcula_perdida(*parametros):
    #red.fc1.weight.data = 
    params = []
    n_params = []
    i=0
    n_dim = 0
    #parametros = list(parametros)
    for param in parametros:
        params.append(param)#recibiria un solo tensor con todos los pesos
    for r_param in red.parameters():
        p_partida = n_dim
        print("shape: " + str(r_param.shape))
        n_dim = r_param.size(0)*(r_param.size(1) if r_param.dim() == 2 else 1) + p_partida#se obtiene la dimension del primer conjunto de pparametros de la red
        print("n_dim: " + str(n_dim) + " p_partida: " + str(p_partida))
        #print("primer vector: " + str(params[0][p_partida:n_dim]))
        n_params.append(params[0][p_partida:n_dim])
        print("primer vector: " + str(n_params[i]))
        n_params[i] = n_params[i].view(r_param.shape)#se le da la forma del parametro correspondiente a los parametros que llegan como entrada
        print("segundo vector: " + str(n_params[i]))
        i = i+1
    #print([b for b in red.parameters()]
    l1 = F.linear(entrada,n_params[0],n_params[1])
    #print(params[0])
    #print(params[1])
    #print("Entradal1: " + str(l1))
    l2 = F.linear(l1,n_params[2],n_params[3])
    #print("Entradal2: " + str(l2))
    salida = F.linear(l2,n_params[4],n_params[5])
    #print("Salida: " + str(salida))

    #salida = (entrada)
    criterion = nn.MSELoss()
    return criterion(salida,salida_esperada)


#print([b for b in red.parameters()])


tensor([1., 2., 3., 4., 5., 6., 7., 8.])


In [65]:
#torch.rand(2,2)
a= torch.tensor([1,2,3,4,5,6,7,8,9,10])
print(a.dim())
print(torch.rand(2,5))
print(a.view(2,5))
def pow_reducer(x):
    return x.pow(3).sum()
inputs = torch.rand(10)
print(inputs.dim())
print(torch.autograd.functional.hessian(pow_reducer, inputs))


1
tensor([[0.8883, 0.5990, 0.9390, 0.1919, 0.8274],
        [0.0160, 0.9186, 0.8657, 0.7889, 0.6975]])
tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])
1
tensor([[5.6592, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 1.9605, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 4.8426, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.5648, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 3.5775, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 3.9578, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 4.7752, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.7785, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0

In [60]:
entrada = input
#print(red.fc1.weight.data)
#red.fc1.weight.data = torch.zeros((10,8))
#print(red.fc1.weight.data)
#print(torch.tensor([[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8]]))
#print(red.fc2.weight.data)
#print(red.fc3.weight.data)
v = [_.view(-1) for _ in red.parameters()]
#for i in v:
 #   print(i)
v = torch.cat([_.view(-1) for _ in red.parameters()], dim = 0)#concatena los paremetros de la red en un solo vector unidimensional
#print(v)
p = calcula_perdida(v)
#print(len(v))
#p = calcula_perdida(v[0],v[1],v[2],v[3],v[4],v[5])
#print(red(entrada))
print(p)

shape: torch.Size([10, 8])
n_dim: 80 p_partida: 0
primer vector: tensor([ 0.1164,  0.2900, -0.0291, -0.0216,  0.2039,  0.1715, -0.2000,  0.1696,
        -0.0674,  0.2430, -0.3349,  0.3140,  0.3342,  0.2254,  0.0340,  0.0556,
        -0.0453,  0.1167,  0.2998,  0.0317,  0.1979, -0.3292,  0.0044, -0.2794,
        -0.2603,  0.0763, -0.0107,  0.0302, -0.2064,  0.0159, -0.1453,  0.0352,
         0.3440, -0.3510, -0.1371,  0.0280,  0.2001,  0.2703, -0.2787, -0.0082,
        -0.2815, -0.2875,  0.1395, -0.1039,  0.1308, -0.2473, -0.2474,  0.0605,
         0.1759, -0.1858, -0.0424, -0.0421, -0.0149,  0.0702, -0.0969,  0.2800,
         0.0935, -0.2574, -0.2462, -0.2338, -0.1046, -0.1525, -0.0649,  0.3412,
        -0.0794,  0.3524,  0.1882, -0.0336, -0.2958, -0.2715, -0.0417, -0.0815,
         0.1595, -0.2941, -0.0761,  0.2392, -0.1874,  0.0783,  0.0819, -0.1737],
       grad_fn=<SliceBackward0>)
segundo vector: tensor([[ 0.1164,  0.2900, -0.0291, -0.0216,  0.2039,  0.1715, -0.2000,  0.1696],
   

In [70]:
print(v.dim())
# class Net(Module):
#     def __init__(self, h, w):
#         super(Net, self).__init__()
#         self.c1 = torch.nn.Conv2d(1, 32, 3, 1, 1)
#         self.f2 = torch.nn.Linear(32 * h * w, 5)


#     def forward(self, x):
#         x = self.c1(x)
#         x = x.view(x.size(0), -1)
#         x = self.f2(x)
#         return x

# def haha(a, b, c, d):
#     p = [a.view(32, 1, 3, 3), b, c.view(5, 32 * 12 * 12), d]
#     x = torch.randn(size=[8, 1, 12, 12], dtype=torch.float32)
#     y = torch.randint(0, 5, [8])
#     x = F.conv2d(x, p[0], p[1], 1, 1)
#     x = x.view(x.size(0), -1)
#     x = F.linear(x, p[2], p[3])
#     loss = F.cross_entropy(x, y)
#     return loss
h = torch.autograd.functional.hessian(calcula_perdida, v)
#print(len(list(a)))
print(len(list(a)[0]))
print(h.dim())
print(h.shape)

#print(h = torch.autograd.functional.hessian(haha, tuple([_.view(-1) for _ in net.parameters()])))

1
shape: torch.Size([10, 8])
n_dim: 80 p_partida: 0
primer vector: tensor([ 0.1164,  0.2900, -0.0291, -0.0216,  0.2039,  0.1715, -0.2000,  0.1696,
        -0.0674,  0.2430, -0.3349,  0.3140,  0.3342,  0.2254,  0.0340,  0.0556,
        -0.0453,  0.1167,  0.2998,  0.0317,  0.1979, -0.3292,  0.0044, -0.2794,
        -0.2603,  0.0763, -0.0107,  0.0302, -0.2064,  0.0159, -0.1453,  0.0352,
         0.3440, -0.3510, -0.1371,  0.0280,  0.2001,  0.2703, -0.2787, -0.0082,
        -0.2815, -0.2875,  0.1395, -0.1039,  0.1308, -0.2473, -0.2474,  0.0605,
         0.1759, -0.1858, -0.0424, -0.0421, -0.0149,  0.0702, -0.0969,  0.2800,
         0.0935, -0.2574, -0.2462, -0.2338, -0.1046, -0.1525, -0.0649,  0.3412,
        -0.0794,  0.3524,  0.1882, -0.0336, -0.2958, -0.2715, -0.0417, -0.0815,
         0.1595, -0.2941, -0.0761,  0.2392, -0.1874,  0.0783,  0.0819, -0.1737],
       grad_fn=<SliceBackward0>)
segundo vector: tensor([[ 0.1164,  0.2900, -0.0291, -0.0216,  0.2039,  0.1715, -0.2000,  0.1696],
 

In [79]:
grad_f = torch.autograd.grad(calcula_perdida(v), v)[0]
print(grad_f.shape)

shape: torch.Size([10, 8])
n_dim: 80 p_partida: 0
primer vector: tensor([ 0.1164,  0.2900, -0.0291, -0.0216,  0.2039,  0.1715, -0.2000,  0.1696,
        -0.0674,  0.2430, -0.3349,  0.3140,  0.3342,  0.2254,  0.0340,  0.0556,
        -0.0453,  0.1167,  0.2998,  0.0317,  0.1979, -0.3292,  0.0044, -0.2794,
        -0.2603,  0.0763, -0.0107,  0.0302, -0.2064,  0.0159, -0.1453,  0.0352,
         0.3440, -0.3510, -0.1371,  0.0280,  0.2001,  0.2703, -0.2787, -0.0082,
        -0.2815, -0.2875,  0.1395, -0.1039,  0.1308, -0.2473, -0.2474,  0.0605,
         0.1759, -0.1858, -0.0424, -0.0421, -0.0149,  0.0702, -0.0969,  0.2800,
         0.0935, -0.2574, -0.2462, -0.2338, -0.1046, -0.1525, -0.0649,  0.3412,
        -0.0794,  0.3524,  0.1882, -0.0336, -0.2958, -0.2715, -0.0417, -0.0815,
         0.1595, -0.2941, -0.0761,  0.2392, -0.1874,  0.0783,  0.0819, -0.1737],
       grad_fn=<SliceBackward0>)
segundo vector: tensor([[ 0.1164,  0.2900, -0.0291, -0.0216,  0.2039,  0.1715, -0.2000,  0.1696],
   

In [82]:
λ = 0.1
r = -torch.inverse(h+λ*torch.eye(211))*grad_f
print(r)
#-torch.inverse(h+λ*torch.eye(211))

tensor([[ 1.7074e-03, -2.8812e-05, -6.4827e-05,  ...,  1.5211e-02,
         -1.3658e-02,  1.5364e-02],
        [-1.4406e-05,  3.3715e-03, -1.2965e-04,  ...,  3.0422e-02,
         -2.7316e-02,  3.0727e-02],
        [-2.1609e-05, -8.6436e-05,  4.9493e-03,  ...,  4.5633e-02,
         -4.0974e-02,  4.6090e-02],
        ...,
        [ 1.3558e-05,  5.4230e-05,  1.2202e-04,  ...,  1.4715e-01,
         -1.4581e-01,  6.5804e-02],
        [ 5.4495e-06,  2.1798e-05,  4.9046e-05,  ...,  6.5275e-02,
         -2.5756e-02,  2.7539e-02],
        [-1.6037e-05, -6.4148e-05, -1.4433e-04,  ..., -7.7068e-02,
          7.2046e-02, -3.5115e-01]])


In [ ]:

x = torch.randn(1,80)
print(x)
y = []
for i in red.parameters():
    y.append(i.shape)
#x = x.view(y[0])
print(x.view(y[0]))


tensor([[ 1.2425, -2.0265, -0.7171,  0.8465,  1.1031,  0.8568, -0.5701,  0.4621,
         -1.8919,  1.8212,  0.2178, -0.4279, -0.3306, -2.0242,  0.1793, -0.6342,
          0.5306, -0.3990, -1.4124, -0.0128, -1.2783, -0.7999, -0.9947, -0.0745,
          0.5407,  1.7440, -0.6248,  0.2478,  0.1415,  1.3523, -0.6399, -1.1641,
         -0.7785, -1.3825, -0.1487, -1.1846, -1.9734,  0.9720,  0.8780,  0.1155,
          1.0394,  1.2352,  1.3094,  0.6719, -1.3239, -0.2211, -1.4850, -0.1578,
         -1.3046, -1.6374,  0.7868,  1.4017,  0.0231,  0.7787, -0.9604,  0.5887,
          0.6013, -0.5279,  1.2014,  0.2648, -2.1216, -0.2071,  0.0888, -2.6840,
          0.7722, -0.1971,  1.9545, -0.2919, -0.4544, -0.3679, -1.6071, -0.4358,
          0.1476,  1.1260, -0.7250, -1.1016, -0.7317,  0.0610,  0.5086, -0.1533]])
tensor([[ 1.2425, -2.0265, -0.7171,  0.8465,  1.1031,  0.8568, -0.5701,  0.4621],
        [-1.8919,  1.8212,  0.2178, -0.4279, -0.3306, -2.0242,  0.1793, -0.6342],
        [ 0.5306, -0.399

In [ ]:
# Supongamos que tienes dos tensores con diferentes formas
tensor_existente = torch.tensor([[1, 2, 3], [4, 5, 6]])
otro_tensor = torch.tensor([[7, 8], [9, 10],[11,12]])

# Obtén la forma del otro tensor
forma_deseada = otro_tensor.shape

# Ajusta la forma del tensor existente para que coincida con la forma deseada
tensor_ajustado = tensor_existente.view(forma_deseada)

# Alternativamente, puedes usar reshape
# tensor_ajustado = tensor_existente.reshape(forma_deseada)

print("Tensor existente:")
print(tensor_existente)

print("Tensor ajustado con la misma forma que el otro tensor:")
print(tensor_ajustado)

Tensor existente:
tensor([[1, 2, 3],
        [4, 5, 6]])
Tensor ajustado con la misma forma que el otro tensor:
tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [ ]:
def pow_reducer(x):
    x=x.view(-1)
    return x.pow(3).sum()
inputs = torch.Tensor([[2,4],[1,3]])
print(inputs)
torch.autograd.functional.hessian(pow_reducer, inputs)

tensor([[2., 4.],
        [1., 3.]])


tensor([[[[12.,  0.],
          [ 0.,  0.]],

         [[ 0., 24.],
          [ 0.,  0.]]],


        [[[ 0.,  0.],
          [ 6.,  0.]],

         [[ 0.,  0.],
          [ 0., 18.]]]])

In [ ]:
print(torch.Tensor([[2,4],[1,3]]))
print(torch.Tensor([[2,4],[1,3]]).view(-1))


tensor([[2., 4.],
        [1., 3.]])
tensor([2., 4., 1., 3.])


In [ ]:
def pow_r(x):
    return x.pow(3).sum()

print(pow_r(torch.Tensor([2])))

tensor(8.)


In [ ]:
net = Net(12, 12)

print([i.view(-1) for i in net.parameters()][0].size())
print([i for i in net.parameters()][0].size())

t = tuple([_.view(-1) for _ in net.parameters()])

print(torch.randn(size=[8, 1, 12, 12], dtype=torch.float32))
#print(net)
#print(len(t))

torch.Size([288])
torch.Size([32, 1, 3, 3])
tensor([[[[ 5.7037e-01, -1.6220e+00,  2.2039e-01,  ..., -1.8979e+00,
           -1.5416e+00, -5.3563e-01],
          [-1.1947e+00,  2.2494e-01,  1.4591e-01,  ...,  4.6369e-01,
           -1.0561e+00, -8.1643e-01],
          [-7.8351e-01, -6.7065e-01,  6.7817e-01,  ...,  2.3470e-01,
            7.0937e-02,  1.5931e+00],
          ...,
          [-7.5470e-01, -1.5926e-01,  5.1093e-01,  ...,  6.1051e-02,
            1.3519e-01,  4.6800e-01],
          [ 2.7908e-01,  7.1455e-01,  2.5397e-01,  ..., -8.8045e-01,
            9.4286e-01,  2.1376e-01],
          [ 2.5175e+00, -4.4433e-01, -2.6354e-01,  ..., -1.1572e+00,
           -1.5571e+00,  9.0103e-01]]],


        [[[-4.0976e-01, -5.2877e-01, -6.8055e-01,  ...,  1.1446e+00,
           -1.6650e-01, -3.5450e-01],
          [-8.4889e-02,  3.4633e-01,  4.9917e-01,  ...,  1.4496e+00,
            3.3475e+00,  1.2317e+00],
          [-4.7402e-01,  5.1185e-01, -5.0354e-01,  ..., -7.3297e-01,
           -

In [ ]:

#h = torch.autograd.functional.hessian(haha, tuple([_.view(-1) for _ in net.parameters()]))
tuple([_.view(-1) for _ in net.parameters()])

(tensor([ 0.1217, -0.0818, -0.1036,  0.3002,  0.1637, -0.1048,  0.2623,  0.2988,
         -0.2624,  0.1128, -0.0690,  0.2537,  0.3321, -0.1400,  0.0543,  0.3223,
         -0.0853, -0.0464,  0.0765, -0.0377, -0.2048,  0.3262,  0.0286, -0.0862,
         -0.1481, -0.1255,  0.3250,  0.2934,  0.1509,  0.2734,  0.0445, -0.0381,
         -0.1065,  0.0958,  0.2534,  0.0984,  0.0806,  0.0021,  0.2244, -0.1927,
         -0.1488,  0.0710, -0.0175, -0.1059,  0.1912,  0.2350,  0.1904, -0.0048,
         -0.1818,  0.1958, -0.0474,  0.0634, -0.2812, -0.1592, -0.1451, -0.0265,
         -0.0242, -0.2434, -0.0942,  0.1893,  0.1298, -0.2936,  0.1334, -0.1612,
          0.0079,  0.2406,  0.1352,  0.2592, -0.2827,  0.2473, -0.2747, -0.1128,
         -0.0998,  0.3259,  0.2503,  0.0906, -0.0950, -0.1080,  0.0297,  0.2630,
         -0.2460,  0.1935, -0.1856, -0.0456,  0.2585,  0.1985,  0.0689,  0.0778,
         -0.0363, -0.0353,  0.2892,  0.2555, -0.0505, -0.2110, -0.1705,  0.1030,
          0.2529,  0.0185,  

In [ ]:


print(type(h))

NameError: name 'h' is not defined