In [1]:
import torch
import numpy as np
from torch.nn import Module
import torch.nn as nn
import torch.nn.functional as F



class Net(Module):
    def __init__(self, h, w):
        super(Net, self).__init__()
        self.c1 = torch.nn.Conv2d(1, 32, 3, 1, 1)
        self.f2 = torch.nn.Linear(32 * h * w, 5)

    def forward(self, x):
        x = self.c1(x)
        x = x.view(x.size(0), -1)
        x = self.f2(x)
        return x

class NARNN(Module):
    def __init__(self, input_dim, hidden_dim, output_dim, num_layers):
        super(NARNN, self).__init__()
        #self.hidden_dim = hidden_dim
        #self.num_layers = num_layers
        #self.lstm = nn.LSTM(input_dim, hidden_dim, num_layers, batch_first=True)#capa lstm
        #self.fc1 = nn.Linear(hidden_dim, output_dim)#capa lineal
        self.fc1 = nn.Linear(input_dim,10)
        self.fc2 = nn.Linear(10,10)
        self.fc3 = nn.Linear(10,output_dim)

    def forward(self, x):
        """h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_dim).requires_grad_()#Crea tensores con las dimensiones especificadas
        c0 = torch.zeros(self.num_layers, x.size(0), self.hidden_dim).requires_grad_()

        out, _ = self.lstm(x, (h0.detach(), c0.detach()))

        out = self.fc1(out[:, -1, :]) 
        return out"""
        tan_sigmoid = lambda a : F.tanh(F.sigmoid(a))
        x = tan_sigmoid(self.fc1(x))
        #print(y)
        #x = torch.sigmoid(self.fc1(x))
        #print(x)
        x = F.logsigmoid(self.fc2(x))
        x = self.fc3(x)
        return x
    
def fun(a, b, c, d):
    p = [a.view(32, 1, 3, 3), b, c.view(5, 32 * 12 * 12), d]
    x = torch.randn(size=[8, 1, 12, 12], dtype=torch.float32)
    y = torch.randint(0, 5, [8])
    x = F.conv2d(x, p[0], p[1], 1, 1)
    x = x.view(x.size(0), -1)
    x = F.linear(x, p[2], p[3])
    loss = F.cross_entropy(x, y)
    return loss

red = NARNN(input_dim=8, hidden_dim=0, output_dim=1, num_layers=0)
input = torch.Tensor([1,2,3,4,5,6,7,8])

print(input)
entrada = input #la entrada se da como un parametro global
salida_esperada = torch.tensor([-0.0834]) #lo mismo para la salida esperada
λ = 0.1

# def calcula_perdida(*parametros):
#     #red.fc1.weight.data = 
#     params = []
#     i=0
#     for param in parametros:
#         params.append(param)
#         #print(param)
#     for r_param in red.parameters():
#         params[i].view(r_param.shape)#se le da la forma del parametro correspondiente a los parametros que llegan como entrada
#         r_param = params[i]
#         i = i+1
#     #print([b for b in red.parameters()])
#     salida = red(entrada)
#     criterion = nn.MSELoss()
#     return criterion(salida,salida_esperada)

# def calcula_perdida(*parametros):
#     #red.fc1.weight.data = 
#     params = []
#     i=0
#     #parametros = list(parametros)
#     for param in parametros:
#         params.append(param)
#         print(param)
#     for r_param in red.parameters():
#         params[i] = params[i].view(r_param.shape)#se le da la forma del parametro correspondiente a los parametros que llegan como entrada
#         # r_param = params[i]
#         i = i+1
#     #print([b for b in red.parameters()]
#     l1 = F.linear(entrada,params[0],params[1])
#     #print(params[0])
#     #print(params[1])
#     #print("Entradal1: " + str(l1))
#     l2 = F.linear(l1,params[2],params[3])
#     #print("Entradal2: " + str(l2))
#     salida = F.linear(l2,params[4],params[5])
#     #print("Salida: " + str(salida))

#     #salida = (entrada)
#     criterion = nn.MSELoss()
#     return criterion(salida,salida_esperada)

def calcula_perdida(*parametros):
    #red.fc1.weight.data = 
    params = []
    n_params = []
    i=0
    n_dim = 0
    #parametros = list(parametros)
    for param in parametros:
        params.append(param)#recibiria un solo tensor con todos los pesos
    for r_param in red.parameters():
        p_partida = n_dim
        print("shape: " + str(r_param.shape))
        n_dim = r_param.size(0)*(r_param.size(1) if r_param.dim() == 2 else 1) + p_partida#se obtiene la dimension del primer conjunto de pparametros de la red
        print("n_dim: " + str(n_dim) + " p_partida: " + str(p_partida))
        #print("primer vector: " + str(params[0][p_partida:n_dim]))
        n_params.append(params[0][p_partida:n_dim])
        print("primer vector: " + str(n_params[i]))
        n_params[i] = n_params[i].view(r_param.shape)#se le da la forma del parametro correspondiente a los parametros que llegan como entrada
        print("segundo vector: " + str(n_params[i]))
        i = i+1
    #print([b for b in red.parameters()]
    l1 = F.linear(entrada,n_params[0],n_params[1])
    #print(params[0])
    #print(params[1])
    #print("Entradal1: " + str(l1))
    l2 = F.linear(l1,n_params[2],n_params[3])
    #print("Entradal2: " + str(l2))
    salida = F.linear(l2,n_params[4],n_params[5])
    #print("Salida: " + str(salida))

    #salida = (entrada)
    criterion = nn.MSELoss()
    return criterion(salida,salida_esperada)


#print([b for b in red.parameters()])


tensor([1., 2., 3., 4., 5., 6., 7., 8.])


In [2]:
#torch.rand(2,2)
a= torch.tensor([1,2,3,4,5,6,7,8,9,10])
print(a.dim())
print(torch.rand(2,5))
print(a.view(2,5))
def pow_reducer(x):
    return x.pow(3).sum()
inputs = torch.rand(10)
print(inputs.dim())
print(torch.autograd.functional.hessian(pow_reducer, inputs))


1
tensor([[0.5362, 0.9088, 0.9564, 0.1839, 0.2225],
        [0.9121, 0.2969, 0.3343, 0.4736, 0.2443]])
tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])
1
tensor([[3.7634, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 2.6036, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.3099, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 3.8268, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.8000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.9504, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 4.8396, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 4.9074, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0

In [3]:
entrada = input
#print(red.fc1.weight.data)
#red.fc1.weight.data = torch.zeros((10,8))
#print(red.fc1.weight.data)
#print(torch.tensor([[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8]]))
#print(red.fc2.weight.data)
#print(red.fc3.weight.data)
v = [_.view(-1) for _ in red.parameters()]
#for i in v:
 #   print(i)
v = torch.cat([_.view(-1) for _ in red.parameters()], dim = 0)#concatena los paremetros de la red en un solo vector unidimensional
#print(v)
p = calcula_perdida(v)
#print(len(v))
#p = calcula_perdida(v[0],v[1],v[2],v[3],v[4],v[5])
#print(red(entrada))
print(p)

shape: torch.Size([10, 8])
n_dim: 80 p_partida: 0
primer vector: tensor([-0.1959,  0.3342, -0.2366,  0.2364, -0.1655,  0.3015, -0.3058, -0.1338,
         0.1965,  0.1493, -0.1877,  0.3120, -0.1346,  0.2856, -0.1745, -0.0723,
        -0.1171, -0.2553, -0.2782, -0.2398, -0.1057,  0.0910,  0.3203, -0.0495,
        -0.0040,  0.3270,  0.0104, -0.2153, -0.1081,  0.1247,  0.3139,  0.2591,
         0.3039, -0.2032,  0.1952,  0.3196,  0.1710,  0.2821,  0.3091,  0.2921,
         0.2477, -0.2997, -0.3333, -0.0167, -0.1838,  0.1239,  0.0974, -0.2778,
        -0.1398,  0.3071, -0.0106, -0.0127,  0.0923, -0.0806,  0.1086,  0.0280,
         0.0204,  0.0151,  0.0727, -0.0670,  0.0105, -0.0888,  0.3277, -0.2437,
         0.2420,  0.0282,  0.3534,  0.2636, -0.0675, -0.2400,  0.1264, -0.2758,
        -0.0225, -0.0685,  0.2602, -0.1006, -0.0839,  0.0710,  0.2769,  0.3441],
       grad_fn=<SliceBackward0>)
segundo vector: tensor([[-0.1959,  0.3342, -0.2366,  0.2364, -0.1655,  0.3015, -0.3058, -0.1338],
   

In [4]:
print(v.dim())
# class Net(Module):
#     def __init__(self, h, w):
#         super(Net, self).__init__()
#         self.c1 = torch.nn.Conv2d(1, 32, 3, 1, 1)
#         self.f2 = torch.nn.Linear(32 * h * w, 5)


#     def forward(self, x):
#         x = self.c1(x)
#         x = x.view(x.size(0), -1)
#         x = self.f2(x)
#         return x

# def haha(a, b, c, d):
#     p = [a.view(32, 1, 3, 3), b, c.view(5, 32 * 12 * 12), d]
#     x = torch.randn(size=[8, 1, 12, 12], dtype=torch.float32)
#     y = torch.randint(0, 5, [8])
#     x = F.conv2d(x, p[0], p[1], 1, 1)
#     x = x.view(x.size(0), -1)
#     x = F.linear(x, p[2], p[3])
#     loss = F.cross_entropy(x, y)
#     return loss
h = torch.autograd.functional.hessian(calcula_perdida, v)
#print(len(list(a)))
#print(len(list(a)[0]))
print(h.dim())
print(h.shape)

#print(h = torch.autograd.functional.hessian(haha, tuple([_.view(-1) for _ in net.parameters()])))

1
shape: torch.Size([10, 8])
n_dim: 80 p_partida: 0
primer vector: tensor([-0.1959,  0.3342, -0.2366,  0.2364, -0.1655,  0.3015, -0.3058, -0.1338,
         0.1965,  0.1493, -0.1877,  0.3120, -0.1346,  0.2856, -0.1745, -0.0723,
        -0.1171, -0.2553, -0.2782, -0.2398, -0.1057,  0.0910,  0.3203, -0.0495,
        -0.0040,  0.3270,  0.0104, -0.2153, -0.1081,  0.1247,  0.3139,  0.2591,
         0.3039, -0.2032,  0.1952,  0.3196,  0.1710,  0.2821,  0.3091,  0.2921,
         0.2477, -0.2997, -0.3333, -0.0167, -0.1838,  0.1239,  0.0974, -0.2778,
        -0.1398,  0.3071, -0.0106, -0.0127,  0.0923, -0.0806,  0.1086,  0.0280,
         0.0204,  0.0151,  0.0727, -0.0670,  0.0105, -0.0888,  0.3277, -0.2437,
         0.2420,  0.0282,  0.3534,  0.2636, -0.0675, -0.2400,  0.1264, -0.2758,
        -0.0225, -0.0685,  0.2602, -0.1006, -0.0839,  0.0710,  0.2769,  0.3441],
       grad_fn=<SliceBackward0>)
segundo vector: tensor([[-0.1959,  0.3342, -0.2366,  0.2364, -0.1655,  0.3015, -0.3058, -0.1338],
 

In [5]:
grad_f = torch.autograd.grad(calcula_perdida(v), v)[0]
print(grad_f.shape)

shape: torch.Size([10, 8])
n_dim: 80 p_partida: 0
primer vector: tensor([-0.1959,  0.3342, -0.2366,  0.2364, -0.1655,  0.3015, -0.3058, -0.1338,
         0.1965,  0.1493, -0.1877,  0.3120, -0.1346,  0.2856, -0.1745, -0.0723,
        -0.1171, -0.2553, -0.2782, -0.2398, -0.1057,  0.0910,  0.3203, -0.0495,
        -0.0040,  0.3270,  0.0104, -0.2153, -0.1081,  0.1247,  0.3139,  0.2591,
         0.3039, -0.2032,  0.1952,  0.3196,  0.1710,  0.2821,  0.3091,  0.2921,
         0.2477, -0.2997, -0.3333, -0.0167, -0.1838,  0.1239,  0.0974, -0.2778,
        -0.1398,  0.3071, -0.0106, -0.0127,  0.0923, -0.0806,  0.1086,  0.0280,
         0.0204,  0.0151,  0.0727, -0.0670,  0.0105, -0.0888,  0.3277, -0.2437,
         0.2420,  0.0282,  0.3534,  0.2636, -0.0675, -0.2400,  0.1264, -0.2758,
        -0.0225, -0.0685,  0.2602, -0.1006, -0.0839,  0.0710,  0.2769,  0.3441],
       grad_fn=<SliceBackward0>)
segundo vector: tensor([[-0.1959,  0.3342, -0.2366,  0.2364, -0.1655,  0.3015, -0.3058, -0.1338],
   

In [22]:
λ = 0.1
r = torch.matmul((-torch.inverse(h+λ*torch.eye(211))),torch.transpose(torch.unsqueeze(grad_f, 0),0, 1))
print(r)
print(torch.transpose(r,0,1))
#-torch.inverse(h+λ*torch.eye(211))

tensor([[ 3.2990e-05,  6.7240e-05,  1.0042e-04,  1.3441e-04,  1.6783e-04,
          2.0080e-04,  2.3457e-04,  2.6874e-04, -1.2525e-05, -2.5565e-05,
         -3.9203e-05, -5.1367e-05, -6.4396e-05, -7.6674e-05, -8.8923e-05,
         -1.0275e-04,  1.1452e-05,  2.2988e-05,  3.4786e-05,  4.6001e-05,
          5.7285e-05,  6.9091e-05,  8.0653e-05,  9.2228e-05, -7.7095e-05,
         -1.5413e-04, -2.3124e-04, -3.0828e-04, -3.8516e-04, -4.6249e-04,
         -5.3936e-04, -6.1693e-04, -1.5815e-04, -3.1613e-04, -4.7464e-04,
         -6.3246e-04, -7.9133e-04, -9.4912e-04, -1.1077e-03, -1.2659e-03,
          6.0543e-05,  1.2106e-04,  1.8146e-04,  2.4189e-04,  3.0221e-04,
          3.6338e-04,  4.2421e-04,  4.8449e-04, -2.1349e-05, -4.3073e-05,
         -6.4198e-05, -8.6457e-05, -1.0718e-04, -1.2774e-04, -1.5152e-04,
         -1.7114e-04,  5.1069e-06,  1.0243e-05,  1.4793e-05,  1.9966e-05,
          2.5591e-05,  2.9368e-05,  3.4965e-05,  4.0624e-05,  6.0240e-06,
          1.2129e-05,  1.8081e-05,  2.

In [23]:
print(r)
#print(torch.transpose(torch.unsqueeze(grad_f, 0),0, 1).shape)

#print(-(0.1*torch.eye(211)+torch.eye(211)))
#print([_.view(-1) for _ in red.parameters()])

tensor([[ 3.2990e-05],
        [ 6.7240e-05],
        [ 1.0042e-04],
        [ 1.3441e-04],
        [ 1.6783e-04],
        [ 2.0080e-04],
        [ 2.3457e-04],
        [ 2.6874e-04],
        [-1.2525e-05],
        [-2.5565e-05],
        [-3.9203e-05],
        [-5.1367e-05],
        [-6.4396e-05],
        [-7.6674e-05],
        [-8.8923e-05],
        [-1.0275e-04],
        [ 1.1452e-05],
        [ 2.2988e-05],
        [ 3.4786e-05],
        [ 4.6001e-05],
        [ 5.7285e-05],
        [ 6.9091e-05],
        [ 8.0653e-05],
        [ 9.2228e-05],
        [-7.7095e-05],
        [-1.5413e-04],
        [-2.3124e-04],
        [-3.0828e-04],
        [-3.8516e-04],
        [-4.6249e-04],
        [-5.3936e-04],
        [-6.1693e-04],
        [-1.5815e-04],
        [-3.1613e-04],
        [-4.7464e-04],
        [-6.3246e-04],
        [-7.9133e-04],
        [-9.4912e-04],
        [-1.1077e-03],
        [-1.2659e-03],
        [ 6.0543e-05],
        [ 1.2106e-04],
        [ 1.8146e-04],
        [ 2

In [8]:

x = torch.randn(1,80)
print(x)
y = []
for i in red.parameters():
    y.append(i.shape)
#x = x.view(y[0])
print(x.view(y[0]))


tensor([[ 0.1163, -1.0359,  0.8326,  0.0294, -0.3389, -1.1610, -0.2600,  1.3225,
          0.2151,  0.6913,  1.1016,  0.3517, -1.0926,  0.1376,  0.2224, -0.6764,
         -0.3170,  0.9312, -1.2252,  0.5269,  1.4364, -0.1911, -0.0458, -0.0723,
          1.2971,  1.0933, -0.8288,  1.0118,  0.1136, -1.4217, -1.6867,  1.3411,
         -0.2619, -0.8584,  0.4098,  1.6572,  0.7964, -0.5192, -1.0067, -0.4939,
          0.1677, -0.3507, -0.4070, -1.2863,  0.5181, -0.8040,  0.0899,  0.5161,
         -0.8158, -0.2558, -0.0743,  2.2494,  1.4208, -1.4235,  1.3553, -0.0055,
          0.7172,  0.1068,  0.2349,  0.8284,  1.4275,  0.2545,  0.3010,  0.8738,
          1.3722,  0.8892,  0.4251, -0.7980,  0.4930, -2.1455, -0.6002,  0.2468,
          0.2561, -0.2038, -1.0521, -0.2180,  0.3193, -1.3633,  0.1726,  0.2693]])
tensor([[ 0.1163, -1.0359,  0.8326,  0.0294, -0.3389, -1.1610, -0.2600,  1.3225],
        [ 0.2151,  0.6913,  1.1016,  0.3517, -1.0926,  0.1376,  0.2224, -0.6764],
        [-0.3170,  0.931

In [9]:
# Supongamos que tienes dos tensores con diferentes formas
tensor_existente = torch.tensor([[1, 2, 3], [4, 5, 6]])
otro_tensor = torch.tensor([[7, 8], [9, 10],[11,12]])

# Obtén la forma del otro tensor
forma_deseada = otro_tensor.shape

# Ajusta la forma del tensor existente para que coincida con la forma deseada
tensor_ajustado = tensor_existente.view(forma_deseada)

# Alternativamente, puedes usar reshape
# tensor_ajustado = tensor_existente.reshape(forma_deseada)

print("Tensor existente:")
print(tensor_existente)

print("Tensor ajustado con la misma forma que el otro tensor:")
print(tensor_ajustado)

Tensor existente:
tensor([[1, 2, 3],
        [4, 5, 6]])
Tensor ajustado con la misma forma que el otro tensor:
tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [10]:
def pow_reducer(x):
    x=x.view(-1)
    return x.pow(3).sum()
inputs = torch.Tensor([[2,4],[1,3]])
print(inputs)
torch.autograd.functional.hessian(pow_reducer, inputs)

tensor([[2., 4.],
        [1., 3.]])


tensor([[[[12.,  0.],
          [ 0.,  0.]],

         [[ 0., 24.],
          [ 0.,  0.]]],


        [[[ 0.,  0.],
          [ 6.,  0.]],

         [[ 0.,  0.],
          [ 0., 18.]]]])

In [11]:
print(torch.Tensor([[2,4],[1,3]]))
print(torch.Tensor([[2,4],[1,3]]).view(-1))


tensor([[2., 4.],
        [1., 3.]])
tensor([2., 4., 1., 3.])


In [12]:
def pow_r(x):
    return x.pow(3).sum()

print(pow_r(torch.Tensor([2])))

tensor(8.)


In [13]:
net = Net(12, 12)

print([i.view(-1) for i in net.parameters()][0].size())
print([i for i in net.parameters()][0].size())

t = tuple([_.view(-1) for _ in net.parameters()])

print(torch.randn(size=[8, 1, 12, 12], dtype=torch.float32))
#print(net)
#print(len(t))

torch.Size([288])
torch.Size([32, 1, 3, 3])
tensor([[[[-0.1983, -1.9691,  0.0434,  ..., -1.3908,  0.4771, -0.3967],
          [-1.1117,  1.4040, -0.6951,  ...,  0.6863, -0.0186,  0.9661],
          [-0.1227,  0.9660,  0.9239,  ..., -0.7129, -1.0009,  1.2682],
          ...,
          [-0.2937, -1.8352,  0.6319,  ...,  0.6301,  1.0036,  0.1321],
          [-0.1069,  0.1753,  1.9536,  ..., -1.3419, -2.1442,  0.1459],
          [-0.9335, -0.2808, -0.4531,  ...,  1.2536, -1.7289,  0.6452]]],


        [[[-1.2618, -0.5357,  0.1832,  ..., -1.1228, -0.5770, -2.1551],
          [-0.5711, -0.0169,  0.3976,  ..., -0.2121, -0.0506,  0.4513],
          [ 1.3490,  2.0045, -0.8415,  ..., -0.4678, -0.1075, -0.7057],
          ...,
          [ 0.6545,  1.0627,  0.6962,  ...,  0.1561, -1.2382,  0.4118],
          [ 0.3219,  0.9007,  1.0146,  ..., -0.7255, -0.7326, -0.4443],
          [ 1.1722, -1.3391, -1.1455,  ..., -0.7805, -0.1412, -0.6500]]],


        [[[-0.3720,  3.1226, -1.0307,  ..., -1.2306, -

In [14]:

#h = torch.autograd.functional.hessian(haha, tuple([_.view(-1) for _ in net.parameters()]))
tuple([_.view(-1) for _ in net.parameters()])

(tensor([-1.0822e-01, -6.4565e-02, -1.7312e-01, -1.4084e-01,  2.7732e-04,
          3.2908e-01,  3.0664e-01,  2.0747e-01, -2.5428e-01, -3.2957e-01,
         -1.9952e-01, -1.9029e-01,  2.3390e-01, -2.7291e-01, -2.5889e-01,
          1.4640e-01,  1.2072e-01,  1.6149e-01,  2.7986e-01,  2.8060e-01,
          3.1479e-01, -3.2459e-01,  1.6795e-01, -1.9119e-01, -6.2354e-02,
         -6.2312e-02,  2.0500e-01,  2.3773e-01, -1.2552e-01,  3.2771e-01,
          1.8885e-01, -2.4989e-01,  2.6277e-01, -2.9609e-01, -3.4744e-02,
          1.0740e-01, -2.9994e-02,  1.5956e-01,  7.0270e-02,  2.6984e-01,
          4.3494e-02,  1.4707e-01,  2.1189e-01, -7.7057e-02,  2.3074e-01,
          1.1717e-01,  2.6989e-01, -7.5095e-02, -1.2888e-01, -2.1737e-01,
         -2.7852e-01, -1.2524e-01, -2.8630e-01, -2.1395e-01,  2.0479e-01,
          1.1009e-01,  1.6142e-01,  2.8751e-01,  3.2095e-01, -1.1432e-01,
         -6.7380e-02,  1.4659e-01, -2.0638e-01,  1.4246e-02, -4.1830e-02,
          5.3237e-02, -1.9791e-01, -3.

In [4]:
import levenberg_marquardt as lm

red = NARNN(input_dim=8, hidden_dim=0, output_dim=1, num_layers=0)
#input = torch.Tensor([1,2,3,4,5,6,7,8])

# print(input)
entrada = input #la entrada se da como un parametro global
salida_esperada = torch.tensor([-0.0834]) #lo mismo para la salida esperada
# λ = 0.1

lm = LM(red)
lm.exec()

# v = torch.cat([_.view(-1) for _ in red.parameters()], dim = 0)#concatena los paremetros de la red en un solo vector unidimensional
# h = torch.autograd.functional.hessian(lm.calcula_perdida, v) #calculamos la matriz hessiana
# grad_f = torch.autograd.grad(lm.calcula_perdida(v), v)[0] #calculamos el gradiente de la funcion
# r = -torch.inverse(h+λ*torch.eye(211))*torch.transpose(grad_f)


AttributeError: 'tuple' object has no attribute 'view'