In [2]:
import torch
import numpy as np
from torch.nn import Module
import torch.nn as nn
import torch.nn.functional as F

class Net(Module):
    def __init__(self, h, w):
        super(Net, self).__init__()
        self.c1 = torch.nn.Conv2d(1, 32, 3, 1, 1)
        self.f2 = torch.nn.Linear(32 * h * w, 5)

    def forward(self, x):
        x = self.c1(x)
        x = x.view(x.size(0), -1)
        x = self.f2(x)
        return x

class NARNN(Module):
    def __init__(self, input_dim, hidden_dim, output_dim, num_layers):
        super(NARNN, self).__init__()
        #self.hidden_dim = hidden_dim
        #self.num_layers = num_layers
        #self.lstm = nn.LSTM(input_dim, hidden_dim, num_layers, batch_first=True)#capa lstm
        #self.fc1 = nn.Linear(hidden_dim, output_dim)#capa lineal
        self.fc1 = nn.Linear(input_dim,10)
        self.fc2 = nn.Linear(10,10)
        self.fc3 = nn.Linear(10,output_dim)

    def forward(self, x):
        """h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_dim).requires_grad_()#Crea tensores con las dimensiones especificadas
        c0 = torch.zeros(self.num_layers, x.size(0), self.hidden_dim).requires_grad_()

        out, _ = self.lstm(x, (h0.detach(), c0.detach()))

        out = self.fc1(out[:, -1, :]) 
        return out"""
        tan_sigmoid = lambda a : F.tanh(F.sigmoid(a))
        x = tan_sigmoid(self.fc1(x))
        #print(y)
        #x = torch.sigmoid(self.fc1(x))
        #print(x)
        x = F.logsigmoid(self.fc2(x))
        x = self.fc3(x)
        return x
    
def fun(a, b, c, d):
    p = [a.view(32, 1, 3, 3), b, c.view(5, 32 * 12 * 12), d]
    x = torch.randn(size=[8, 1, 12, 12], dtype=torch.float32)
    y = torch.randint(0, 5, [8])
    x = F.conv2d(x, p[0], p[1], 1, 1)
    x = x.view(x.size(0), -1)
    x = F.linear(x, p[2], p[3])
    loss = F.cross_entropy(x, y)
    return loss

red = NARNN(input_dim=8, hidden_dim=0, output_dim=1, num_layers=0)
input = torch.Tensor(1,2,3,4,5,6,7,8)
red(input)
print(type(red.parameters()))
entrada = torch.tensor([]) #la entrada se da como un parametro global
salida_esperada = torch.tensor([]) #lo mismo para la salida esperada

def calcula_perdida(*parametros):
    #red.fc1.weight.data = 
    params = []
    for param in parametros:
        params.append(param)
    for r_param in red.parameters():
        params[i].view(r_param.shape)#se le da la forma del parametro correspondiente a los aprametros que llegan como entrada
        r_param = params[i]
        i = i+1
    salida = red(entrada)
    criterion = nn.MSELoss()
    return criterion(salida,salida_esperada)
    





<class 'generator'>


/home/miguel/anaconda3/lib/python3.9/site-packages/torch/nn/functional.py:1944: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
/home/miguel/anaconda3/lib/python3.9/site-packages/torch/nn/functional.py:1933: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")


In [37]:
#print(red.fc1.weight.data)
red.fc1.weight.data = torch.zeros((10,8))
#print(red.fc1.weight.data)
#print(torch.tensor([[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8]]))
#print(red.fc2.weight.data)
#print(red.fc3.weight.data)
x = torch.randn(1,80)
print(x)
y = []
for i in red.parameters():
    y.append(i.shape)
#x = x.view(y[0])
print(x.view(y[0]))


tensor([[-0.1411,  1.4758,  0.7462, -0.0187, -0.3914,  1.6073,  0.0249, -0.9565,
         -1.2490,  2.1199,  0.8640,  0.0597,  1.0903, -0.0392, -0.9402,  1.8541,
         -0.7999,  1.5906, -0.7604,  1.7112,  0.1158, -0.5146,  0.3822, -1.2885,
          0.6973, -0.0527, -0.7901,  0.8563,  0.7015, -0.8745, -0.9417, -0.7505,
          0.1789, -0.5233,  0.7833, -2.1573, -0.9677, -0.6090, -1.4074, -0.8595,
          0.2788,  0.2573, -1.0860, -0.0619,  1.4888, -2.0524, -1.0924, -0.9561,
         -0.6683,  0.5468, -1.4681, -0.1267,  1.6945, -0.3629, -1.2136, -0.3393,
         -0.2017, -1.0044,  0.0938, -0.7913, -0.4647,  1.6120, -1.1836, -0.0616,
         -0.4828,  0.8668, -1.0124,  0.3047,  0.0153, -0.6259,  0.1596, -0.1110,
          0.5508, -1.5005, -0.6421,  0.4497,  0.4474, -0.9979, -0.6710,  0.3079]])
tensor([[-0.1411,  1.4758,  0.7462, -0.0187, -0.3914,  1.6073,  0.0249, -0.9565],
        [-1.2490,  2.1199,  0.8640,  0.0597,  1.0903, -0.0392, -0.9402,  1.8541],
        [-0.7999,  1.590

In [35]:
# Supongamos que tienes dos tensores con diferentes formas
tensor_existente = torch.tensor([[1, 2, 3], [4, 5, 6]])
otro_tensor = torch.tensor([[7, 8], [9, 10],[11,12]])

# Obtén la forma del otro tensor
forma_deseada = otro_tensor.shape

# Ajusta la forma del tensor existente para que coincida con la forma deseada
tensor_ajustado = tensor_existente.view(forma_deseada)

# Alternativamente, puedes usar reshape
# tensor_ajustado = tensor_existente.reshape(forma_deseada)

print("Tensor existente:")
print(tensor_existente)

print("Tensor ajustado con la misma forma que el otro tensor:")
print(tensor_ajustado)

Tensor existente:
tensor([[1, 2, 3],
        [4, 5, 6]])
Tensor ajustado con la misma forma que el otro tensor:
tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [28]:
def pow_reducer(x):
    x=x.view(-1)
    return x.pow(3).sum()
inputs = torch.Tensor([[2,4],[1,3]])
print(inputs)
torch.autograd.functional.hessian(pow_reducer, inputs)

tensor([[2., 4.],
        [1., 3.]])


tensor([[[[12.,  0.],
          [ 0.,  0.]],

         [[ 0., 24.],
          [ 0.,  0.]]],


        [[[ 0.,  0.],
          [ 6.,  0.]],

         [[ 0.,  0.],
          [ 0., 18.]]]])

In [27]:
print(torch.Tensor([[2,4],[1,3]]))
print(torch.Tensor([[2,4],[1,3]]).view(-1))


tensor([[2., 4.],
        [1., 3.]])
tensor([2., 4., 1., 3.])


In [20]:
def pow_r(x):
    return x.pow(3).sum()

print(pow_r(torch.Tensor([2])))

tensor([8.])


In [16]:
net = Net(12, 12)

print([i.view(-1) for i in net.parameters()][0].size())
print([i for i in net.parameters()][0].size())

t = tuple([_.view(-1) for _ in net.parameters()])

print(torch.randn(size=[8, 1, 12, 12], dtype=torch.float32))
#print(net)
#print(len(t))

torch.Size([288])
torch.Size([32, 1, 3, 3])
tensor([[[[-1.7086e-01, -9.9763e-01,  4.9387e-01,  ..., -2.1957e+00,
            2.1997e-01,  1.0832e+00],
          [ 7.6519e-01,  2.0357e+00,  1.2985e+00,  ..., -6.8119e-02,
           -2.3163e-01, -7.9768e-01],
          [-1.0550e+00, -1.1233e-01, -4.7895e-01,  ..., -2.4745e-01,
            1.1304e-02, -9.5381e-01],
          ...,
          [-6.8423e-01, -1.9927e+00, -7.8542e-01,  ...,  7.4163e-01,
           -1.5225e-01,  8.2589e-01],
          [-1.3133e+00,  1.3756e+00, -1.1276e+00,  ..., -2.6687e-01,
            1.4568e-01, -1.0182e+00],
          [-6.5443e-01, -3.4601e-01,  5.2686e-01,  ...,  6.1969e-01,
           -4.0370e-01,  6.4948e-01]]],


        [[[-1.8940e+00,  2.2573e+00,  1.8935e+00,  ...,  1.3378e+00,
            1.5176e+00, -1.5392e+00],
          [-3.9513e-01, -2.6737e+00, -2.2002e+00,  ...,  5.6577e-01,
           -1.7362e-03,  9.9842e-01],
          [-9.3429e-02,  1.2364e+00, -1.8262e+00,  ..., -3.5580e-01,
            

In [2]:

h = torch.autograd.functional.hessian(haha, tuple([_.view(-1) for _ in net.parameters()]))

: 

: 

In [ ]:


print(type(h))

NameError: name 'h' is not defined