In [1]:
import torch, numpy as np
import torch.nn as nn
import torch.optim as optim
from NARNN import NARNN

criterion = nn.MSELoss()

print(type(criterion))
red_A1 = NARNN(input_dim=8, hidden_dim=0, output_dim=1, num_layers=0)

<class 'torch.nn.modules.loss.MSELoss'>


In [2]:
for p in red_A1.parameters():
    print("param: " + str(p.data))

param: tensor([[ 0.2783,  0.2227,  0.2038,  0.1187, -0.0113,  0.1069,  0.2319,  0.0739],
        [-0.2294,  0.1116,  0.3521, -0.2191,  0.0937,  0.1413,  0.0130, -0.2106],
        [-0.1620,  0.1835,  0.1033, -0.2904,  0.0238,  0.0962,  0.2490,  0.0155],
        [-0.2153,  0.2543,  0.0593,  0.1017,  0.2695,  0.3012,  0.1410,  0.0133],
        [ 0.0976, -0.2911,  0.3376, -0.3454,  0.1768, -0.3010, -0.2370,  0.2148],
        [-0.2219, -0.0692,  0.3108,  0.1200,  0.2536,  0.0757,  0.2455, -0.1522],
        [-0.0592, -0.1702,  0.3058, -0.2832, -0.2144,  0.2021,  0.0814, -0.3482],
        [-0.0352, -0.2680,  0.1825,  0.2927, -0.2879,  0.2107,  0.2917,  0.0661],
        [ 0.1063,  0.0721,  0.0807,  0.0172,  0.1377,  0.2261,  0.3244, -0.3215],
        [-0.0103,  0.1867, -0.1124,  0.3210, -0.2241, -0.0999, -0.2604, -0.3089]])
param: tensor([ 0.1069, -0.0916,  0.3147, -0.1903, -0.1747, -0.3330,  0.1276, -0.0919,
         0.0906, -0.1138])
param: tensor([[-0.0738, -0.0498, -0.2000, -0.0822, -0.050

In [3]:
def my_MSEloss(params):
    c = 0
    for param in red_A1.parameters():
        param = params[c]
        print(param)
        c = c + 1

for j in red_A1.parameters():
    print(j)

my_MSEloss([torch.zeros_like(tensor) for tensor in red_A1.parameters()])
#for i in red_A1.parameters():
 #   print(i)

Parameter containing:
tensor([[ 0.2783,  0.2227,  0.2038,  0.1187, -0.0113,  0.1069,  0.2319,  0.0739],
        [-0.2294,  0.1116,  0.3521, -0.2191,  0.0937,  0.1413,  0.0130, -0.2106],
        [-0.1620,  0.1835,  0.1033, -0.2904,  0.0238,  0.0962,  0.2490,  0.0155],
        [-0.2153,  0.2543,  0.0593,  0.1017,  0.2695,  0.3012,  0.1410,  0.0133],
        [ 0.0976, -0.2911,  0.3376, -0.3454,  0.1768, -0.3010, -0.2370,  0.2148],
        [-0.2219, -0.0692,  0.3108,  0.1200,  0.2536,  0.0757,  0.2455, -0.1522],
        [-0.0592, -0.1702,  0.3058, -0.2832, -0.2144,  0.2021,  0.0814, -0.3482],
        [-0.0352, -0.2680,  0.1825,  0.2927, -0.2879,  0.2107,  0.2917,  0.0661],
        [ 0.1063,  0.0721,  0.0807,  0.0172,  0.1377,  0.2261,  0.3244, -0.3215],
        [-0.0103,  0.1867, -0.1124,  0.3210, -0.2241, -0.0999, -0.2604, -0.3089]],
       requires_grad=True)
Parameter containing:
tensor([ 0.1069, -0.0916,  0.3147, -0.1903, -0.1747, -0.3330,  0.1276, -0.0919,
         0.0906, -0.1138], r

In [4]:
print(red_A1.parameters)

<bound method Module.parameters of NARNN(
  (fc1): Linear(in_features=8, out_features=10, bias=True)
  (fc2): Linear(in_features=10, out_features=10, bias=True)
  (fc3): Linear(in_features=10, out_features=1, bias=True)
)>


In [5]:
print(torch.rand(2, 2))

for i in torch.rand(2, 2):
    print(i)
    print(type(i))


tensor([[0.7509, 0.7377],
        [0.2890, 0.5863]])
tensor([0.4134, 0.6993])
<class 'torch.Tensor'>
tensor([0.9921, 0.9088])
<class 'torch.Tensor'>


In [6]:
import torch

class Net(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.a = torch.nn.Parameter(torch.tensor([1.0, -1.0, 2.0]))
        self.b = torch.nn.Parameter(torch.tensor([2.0, -2.0, -1.0]))

    def forward(self, x):
        output = (x * self.a.unsqueeze(0) ** 3 + x * self.b.unsqueeze(0) ** 3).sum(dim=1)
        return output

x = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
y = torch.tensor([1.0, 2.0])
net = Net()

def compute_z(*net_parameters):
    # Is there a proper way to set the parameters that works with hessian?
    for p_src, p_dst in zip(net_parameters, net.parameters()):
        p_dst.data = p_src.data

    output = net(x)
    z = ((output - y)**2).mean()
    return z

# strict=True raises exception, allowing non-strict for demonstration
hessians = torch.autograd.functional.hessian(compute_z, tuple(net.parameters()))

param_names = [n for n, _ in net.named_parameters()]
for d_name, d_hessians in zip(param_names, hessians):
    for dd_name, dd_hessian in zip(param_names, d_hessians):
        print(f'dz/d{dd_name}d{d_name} = \n{dd_hessian}\n')

dz/dada = 
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

dz/dbda = 
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

dz/dadb = 
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

dz/dbdb = 
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])



In [7]:
#optimizer = optim.SGD(red.parameters(), lr=0.1, momentum=0.4)#,maximize=True)
#optimizer.zero_grad()
output = red_A1(torch.Tensor([1,2,3,4,5,6,7,8]))
target = torch.Tensor([1,2,3,4,5,6,7,8])
loss = criterion(output, target)
print(loss)
print(type(criterion))
print(type(loss.grad_fn))

print(output)
print(type(output.grad_fn))

t = []

for c in red_A1.parameters():
    print(type(c.data))
    t.append(c.data)

#torch.cat(,dim = 0)
# print(t)

h = torch.autograd.functional.hessian(loss.grad_fn, torch.rand(2, 2))

tensor(29.1231, grad_fn=<MseLossBackward0>)
<class 'torch.nn.modules.loss.MSELoss'>
<class 'MseLossBackward0'>
tensor([-0.3860], grad_fn=<AddBackward0>)
<class 'AddBackward0'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>


/home/miguel/anaconda3/lib/python3.9/site-packages/torch/nn/functional.py:1944: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
/home/miguel/anaconda3/lib/python3.9/site-packages/torch/nn/functional.py:1933: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")
/home/miguel/anaconda3/lib/python3.9/site-packages/torch/nn/modules/loss.py:529: UserWarning: Using a target size (torch.Size([8])) that is different to the input size (torch.Size([1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


RuntimeError: The size of tensor a (8) must match the size of tensor b (2) at non-singleton dimension 1

In [ ]:




print(loss)
loss.backward()
h = torch.autograd.functional.hessian(loss)#calcula el hessiana de la funcion de perdida
h+ lambda 
print(loss.backward())
optimizer.step()

SyntaxError: invalid syntax (3211808025.py, line 4)

In [ ]:
criterion = nn.MSELoss()