In [2]:
import torch, numpy as np
import torch.nn as nn
import torch.optim as optim
from NARNN import NARNN

criterion = nn.MSELoss()

print(type(criterion))
red_A1 = NARNN(input_dim=8, hidden_dim=0, output_dim=1, num_layers=0)

<class 'torch.nn.modules.loss.MSELoss'>


In [3]:
for p in red_A1.parameters():
    print("param: " + str(p.data))

param: tensor([[ 0.1365,  0.1475,  0.0727, -0.2675, -0.3428, -0.2591, -0.3029, -0.1742],
        [-0.1430, -0.0163, -0.3324, -0.3178,  0.1835, -0.2752, -0.1677, -0.3370],
        [ 0.2560,  0.0464, -0.0847,  0.1569,  0.1387, -0.0720, -0.2338, -0.0957],
        [ 0.3159,  0.2725,  0.3294, -0.1795,  0.1986, -0.0058, -0.0068,  0.1954],
        [ 0.1210,  0.1950,  0.0539,  0.1472, -0.2765, -0.1109, -0.0905,  0.0989],
        [ 0.3171, -0.1050,  0.1900, -0.1380, -0.0681, -0.1221,  0.0766,  0.1762],
        [-0.2288,  0.2587, -0.1251,  0.2546, -0.1502, -0.1607, -0.1101,  0.0111],
        [-0.1900, -0.3452, -0.1824, -0.2005,  0.1285, -0.2236,  0.0646, -0.0204],
        [-0.1820, -0.3059, -0.2245, -0.2715,  0.0053, -0.0027, -0.2166, -0.0728],
        [ 0.3393,  0.3314,  0.0455,  0.2558,  0.0813,  0.2907,  0.1761, -0.2713]])
param: tensor([ 0.2669, -0.1122,  0.0157,  0.2356, -0.2959,  0.2585,  0.1946,  0.0431,
         0.1356,  0.3215])
param: tensor([[ 0.0075, -0.0612, -0.2975, -0.1153, -0.252

In [4]:
def my_MSEloss(params):
    c = 0
    for param in red_A1.parameters():
        param = params[c]
        print(param)
        c = c + 1

for j in red_A1.parameters():
    print(j)

my_MSEloss([torch.zeros_like(tensor) for tensor in red_A1.parameters()])
#for i in red_A1.parameters():
 #   print(i)

Parameter containing:
tensor([[ 0.1365,  0.1475,  0.0727, -0.2675, -0.3428, -0.2591, -0.3029, -0.1742],
        [-0.1430, -0.0163, -0.3324, -0.3178,  0.1835, -0.2752, -0.1677, -0.3370],
        [ 0.2560,  0.0464, -0.0847,  0.1569,  0.1387, -0.0720, -0.2338, -0.0957],
        [ 0.3159,  0.2725,  0.3294, -0.1795,  0.1986, -0.0058, -0.0068,  0.1954],
        [ 0.1210,  0.1950,  0.0539,  0.1472, -0.2765, -0.1109, -0.0905,  0.0989],
        [ 0.3171, -0.1050,  0.1900, -0.1380, -0.0681, -0.1221,  0.0766,  0.1762],
        [-0.2288,  0.2587, -0.1251,  0.2546, -0.1502, -0.1607, -0.1101,  0.0111],
        [-0.1900, -0.3452, -0.1824, -0.2005,  0.1285, -0.2236,  0.0646, -0.0204],
        [-0.1820, -0.3059, -0.2245, -0.2715,  0.0053, -0.0027, -0.2166, -0.0728],
        [ 0.3393,  0.3314,  0.0455,  0.2558,  0.0813,  0.2907,  0.1761, -0.2713]],
       requires_grad=True)
Parameter containing:
tensor([ 0.2669, -0.1122,  0.0157,  0.2356, -0.2959,  0.2585,  0.1946,  0.0431,
         0.1356,  0.3215], r

In [5]:
print(red_A1.parameters)

<bound method Module.parameters of NARNN(
  (fc1): Linear(in_features=8, out_features=10, bias=True)
  (fc2): Linear(in_features=10, out_features=10, bias=True)
  (fc3): Linear(in_features=10, out_features=1, bias=True)
)>


In [21]:
print(torch.rand(2, 2))

for i in torch.rand(2, 2):
    print(i)
    print(type(i))


tensor([[0.5007, 0.4139],
        [0.9362, 0.1404]])
tensor([0.3402, 0.1389])
<class 'torch.Tensor'>
tensor([0.2854, 0.0563])
<class 'torch.Tensor'>


In [1]:
import torch

class Net(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.a = torch.nn.Parameter(torch.tensor([1.0, -1.0, 2.0]))
        self.b = torch.nn.Parameter(torch.tensor([2.0, -2.0, -1.0]))

    def forward(self, x):
        output = (x * self.a.unsqueeze(0) ** 3 + x * self.b.unsqueeze(0) ** 3).sum(dim=1)
        return output

x = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
y = torch.tensor([1.0, 2.0])
net = Net()

def compute_z(*net_parameters):
    # Is there a proper way to set the parameters that works with hessian?
    for p_src, p_dst in zip(net_parameters, net.parameters()):
        p_dst.data = p_src.data

    output = net(x)
    z = ((output - y)**2).mean()
    return z

# strict=True raises exception, allowing non-strict for demonstration
hessians = torch.autograd.functional.hessian(compute_z, tuple(net.parameters()))

param_names = [n for n, _ in net.named_parameters()]
for d_name, d_hessians in zip(param_names, hessians):
    for dd_name, dd_hessian in zip(param_names, d_hessians):
        print(f'dz/d{dd_name}d{d_name} = \n{dd_hessian}\n')

dz/dada = 
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

dz/dbda = 
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

dz/dadb = 
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

dz/dbdb = 
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])



In [29]:
#optimizer = optim.SGD(red.parameters(), lr=0.1, momentum=0.4)#,maximize=True)
#optimizer.zero_grad()
output = red_A1(torch.Tensor([1,2,3,4,5,6,7,8]))
target = torch.Tensor([1,2,3,4,5,6,7,8])
loss = criterion(output, target)
print(loss)
print(type(criterion))
print(type(loss.grad_fn))

print(output)
print(type(output.grad_fn))

t = []

for c in red_A1.parameters():
    print(type(c.data))
    t.append(c.data)

#torch.cat(,dim = 0)
# print(t)

h = torch.autograd.functional.hessian(loss.grad_fn, torch.rand(2, 2))

tensor(29.6509, grad_fn=<MseLossBackward0>)
<class 'torch.nn.modules.loss.MSELoss'>
<class 'MseLossBackward0'>
tensor([-0.4397], grad_fn=<AddBackward0>)
<class 'AddBackward0'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>


RuntimeError: The size of tensor a (8) must match the size of tensor b (2) at non-singleton dimension 1

In [7]:




print(loss)
loss.backward()
h = torch.autograd.functional.hessian(loss)#calcula el hessiana de la funcion de perdida
h+ lambda 
print(loss.backward())
optimizer.step()

SyntaxError: invalid syntax (3211808025.py, line 4)

In [ ]:
criterion = nn.MSELoss()